### ISSUE TITLE
docker image

### ISSUE THREAD

**Issue by juan11perez** [jziolkowski/tdm#1]
please consider adding docker. Thank you

**Comment by jziolkowski** [comment]
I'll see about it down the road, thanks for suggestion.

**Comment by jziolkowski** [comment]
Let me ask: since TDM doesn't need a server, why you need docker instead of virtualenv?

**Comment by juan11perez** [comment]
I use unraid 
Only docker applications in unraid.

**Comment by andrethomas** [comment]
You're using unraid as a desktop solution?

**Comment by jziolkowski** [comment]
@juan11perez I repeat: this is not a web app. It works on desktop.

**Comment by juan11perez** [comment]
understood, my mistake
