### ISSUE TITLE
Crashes after connecting to MQTT broker

### ISSUE THREAD

**Issue by phoenixtechnam** [jziolkowski/tdm#100]
Hi,
I'm using Windows 10 x64.
TDM crashes after connecting to my MQTT broker (possibly when receiving the first messages, tested with 2 different instances of mosquitto broker).

Tested with 
- tdmgr_0.2.5.exe
- tdmgr_0.2.6.exe
- tdmgr_0.2.6_x86.exe

It briefly shows "connected as..." in the bottom bar, then the program closes without further interaction. No devices are shown before crashing. Is there a way to retrieve some logs?

**Comment by harfordhawk** [comment]
same problem here

**Comment by barbudor** [comment]
@phoenixtechnam @harfordhawk
What is your MQTT broker? 
Any thing specific in your settings? 
I have no issues with latest mosquitto, clear 1883

**Comment by harfordhawk** [comment]
nothing special... mosquito running on a separate local linux machine.. I
use a name and password.. 1883 port...
that is all.

**Comment by barbudor** [comment]
There is a log file in `C:\Users\<yourname>\TDM`
You can configure the logging level in tdm.cfg with an entry `loglevel=DEBUG` in `[General]`

**Comment by harfordhawk** [comment]
here is log output

2020-12-06 12:36:43 [DEBUG] MQTT: Subscribed to tele/#, stat/#, cmnd/#,
+/tele/#, +/stat/#, +/cmnd/#
2020-12-06 12:36:44 [INFO] DISCOVERY: LWT from an unknown device
tele/sonoff1/LWT
2020-12-06 12:36:44 [DEBUG] DISCOVERY: Asking an unknown device for
FullTopic at cmnd/sonoff1/FullTopic
2020-12-06 12:36:44 [INFO] DISCOVERY: LWT from an unknown device
tele/sonoff2/LWT
2020-12-06 12:36:44 [DEBUG] DISCOVERY: Asking an unknown device for
FullTopic at cmnd/sonoff2/FullTopic
2020-12-06 12:36:44 [INFO] DISCOVERY: LWT from an unknown device
tele/shelly1/LWT
2020-12-06 12:36:44 [DEBUG] DISCOVERY: Asking an unknown device for
FullTopic at cmnd/shelly1/FullTopic
2020-12-06 12:36:44 [INFO] DISCOVERY: LWT from an unknown device
tele/RF_Bridge/LWT
2020-12-06 12:36:44 [DEBUG] DISCOVERY: Asking an unknown device for
FullTopic at cmnd/RF_Bridge/FullTopic

**Comment by barbudor** [comment]
Thanks.
Unfortunately, this doesn't give us much help.
No better idea for now

**Comment by jziolkowski** [comment]
Sorry for no reply.

Please run TDM from cmd.exe, it should show some error messages after the crash

**Comment by jziolkowski** [comment]
And fetch the latest repo version, I've added exception logging in case of crash, the log file should have some info.

**Comment by harfordhawk** [comment]
looking for it. I can't see the new windows program

**Comment by jziolkowski** [comment]
Yes, the windows release will come in a day or two. If you are able to do so, try running from repo code if you have python installed. If not, pls wait.

**Comment by jziolkowski** [comment]
Still, running the 0.2.6 from cmd.exe still might give some details

**Comment by harfordhawk** [comment]
Yes I ran it with cmd.exe ... I didn't see any data after crash

**Comment by Jason2866** [comment]
Please try latest release

**Comment by harfordhawk** [comment]
I think my problem was that I am using MQTT on a different server, although
local in my house, I did not realize it has to run on the same server as
HA, so for me it works, but I use another MGTT server, so it won't really
'work' for me as a program.
