### ISSUE TITLE
Crashes when Timer window is opened (Tasmota JSON changed from 'arm' to 'enable')

### ISSUE THREAD

**Issue by alexhk** [jziolkowski/tdm#101]
Tasmota firmware recently changed the timer settings from `arm` to `enable`.

https://tasmota.github.io/docs/Timers/#json-payload-anatomy

When I open the Timer window on a device with Tasmota 8.4.0.3 it crashes.

I installed an older firmware to test, and oipening the window for devices with 8.1 works  fine. 

Not sure which firmware version introduced this change, I only recently noticed this myself.

**Comment by vtainc** [comment]
+1

**Comment by eku** [comment]
The question is how to make TDM work with different versions of Tasmota. A compulsion to the last official version is rather to be rejected.

**Comment by jziolkowski** [comment]
@eku you are right and I am not going to enforce users to the latest version. I'll add some workarounds so I can support as many versions as I can practically can. Currently it's 6.6 up and as long as it makes sense I will keep supporting these

**Comment by Bascht74** [comment]
Hi @GrahamM Really like your software and would love to geht the new version. Do you have any timetable to release it? I really need to use it for timers...
Regards, Sebastian

**Comment by Jason2866** [comment]
@Bascht74  tdm is from jziolkowski ;-)
