### ISSUE TITLE
%hostname% as topic not processed right

### ISSUE THREAD

**Issue by Bascht74** [jziolkowski/tdm#108]
Hello, 

in Tasmota you can enter the hostname as a topic name, so you only have to enter the device names in a few places and have a clean standard that is at the same time easy to read in mqtt. 

Unfortunately TDMGR does not process this correctly. From the discovery it got the hostname, but still the device is not displayed correctly. 

Possibly a processing for this is missing: If %hostname% is entered as topic, TDMGR should get the topic from it. 

I have not found a way to tell TDMGR this myself. 
Currently I have set the topic names statically to the hostnames again.

Greetings and thanks for your great work!

Sebastian

Translated with www.DeepL.com/Translator (free version)

**Comment by jziolkowski** [comment]
I need to rewrite how TDM parses fulltopics in discovery mode. I'll have a look.

**Comment by jziolkowski** [comment]
what tasmota version do you use? I tried setting %hostname% as topic on my test nodemcu and it's not parsed correctly in tasmota

**Comment by Bascht74** [comment]
9.2.0.1

configuration:
![image](https://user-images.githubusercontent.com/66269310/102688879-344ca600-41fa-11eb-8e3a-62e174204762.png)

discovery:
![image](https://user-images.githubusercontent.com/66269310/102688904-678f3500-41fa-11eb-89ae-1f8548a3c2ac.png)

stats of the device:
![image](https://user-images.githubusercontent.com/66269310/102688930-a02f0e80-41fa-11eb-85d4-230c1bcef310.png)

**Comment by Jason2866** [comment]
%hostname% was never official supported to be used for this

**Comment by Bascht74** [comment]
@Jason2866 Is there another way to set a devicename in tasmote in one place and use that for
- hostname, e.g. %devicename%
- mqtt topic, e.g. %devicename%
- friendly name relay 1-4, e.g. %devicename%.1-4

So any way to set one variable and use that for hostname, mqtt, friendlyname and devicename so that they are all the same.

So just set it in one place and all other places will be set accordingly.
Is there a better way? I didn't find it so that I tried out %hostname% in the mqtt topic.

Thx for any tipp about it, 
Sebastian

**Comment by Jason2866** [comment]
The variables you find in my_user_config.h https://github.com/arendst/Tasmota/blob/development/tasmota/my_user_config.h#L123

**Comment by Bascht74** [comment]
@Jason2866 Thank you! 
But I don't find there any of the valid variables like %X, %s, %d, %topic% etc. 
And I don't find any information, which variables are valid for e.g. the topic entry.
maybe I am blind or I don't understand what you mean...

Seb

**Comment by sfromis** [comment]
The docs for [FullTopic](https://tasmota.github.io/docs/MQTT/#fulltopic) does include
```
%hostname% = the hostname of the device as defined through the web UI (default = %s-%04d) or via Hostname command.
```

**Comment by Bascht74** [comment]
OK, then...
