### ISSUE TITLE
Crashes if json in rule

### ISSUE THREAD

**Issue by Dees7** [jziolkowski/tdm#109]
Hello. I have an rule, who contains JSON in code:

      on system#boot do 
	      ruletimer1 300 
      endon 
      on Rules#Timer=1 do 
	      backlog publish2 tele/sdm/STAT {"ENERGY":{"Cost":2.27}}; ruletimer1 300; 
      endon 
      on Switch1#State do 
	      event toggling1=%value% 
      endon 
      on Switch2#State do 
	      event toggling2=%value% 
      endon

If I try to open rules from device with tdm it crashes. 

Tasmota 8.2.0.5

**Comment by Dees7** [comment]
If i send  command "Rule1" with console (in tdm) it works well. So I think trouble in code parser.

**Comment by jziolkowski** [comment]
there were improvements to JSON escaping in tasmota, so please upgrade to a newer version.
There is a workaround for some unescaped JSON in TDM rules reader, but apparently it doesn't catch every issue.
Again, please upgrade Tasmota :)

**Comment by Dees7** [comment]
Works well in 9.2.1
