### ISSUE TITLE
Crashing on Windows 10

### ISSUE THREAD

**Issue by alexgavs** [jziolkowski/tdm#11]
Traceback (most recent call last):
  File "C:\tasmota\tdm-master\tdm.py", line 287, in mqtt_message
    full_topic = loads(msg).get('FullTopic')
  File "C:\Users\alexg\AppData\Local\Programs\Python\Python36-32\lib\json\__init__.py", line 354, in loads
    return _default_decoder.decode(s)
  File "C:\Users\alexg\AppData\Local\Programs\Python\Python36-32\lib\json\decoder.py", line 342, in decode
    raise JSONDecodeError("Extra data", s, end)
json.decoder.JSONDecodeError: Extra data: line 1 column 2 (char 1)

**Comment by jziolkowski** [comment]
please paste the output of command status 0

**Comment by alexgavs** [comment]
![image](https://user-images.githubusercontent.com/2532262/53558357-8c5f7780-3b50-11e9-913e-05159277832b.png)

interface opens and closes after 2 seconds..

**Comment by jziolkowski** [comment]
Yes, I understand. Waiting for output of status 0 from tastmota console.

**Comment by alexgavs** [comment]
Where are saved the settings for mqtt broker? how to change parameters

**Comment by jziolkowski** [comment]
<user directory>/TDM/tdm.cfg

what about that status 0? I can't fix your issue without it.

**Comment by jziolkowski** [comment]
try latest commit and check again

**Comment by jziolkowski** [comment]
Closed due to inactivity.
