### ISSUE TITLE
Exception in thread on "utf8" decode, freeze GUI

### ISSUE THREAD

**Issue by barbudor** [jziolkowski/tdm#114]
Hi,
Originally I saw this only in VSCode, but finally it occurs also when running from the command line

Reproduced on current HEAD as of 22/12/2020 : https://github.com/jziolkowski/tdm/commit/c22809e08ffc8be6fa65365426bdb59991e21f2b

Python version (venv) : 3.8.6 (Windows x64)
pip list (in venv):
```
Package           Version
----------------- -------
astroid           2.4.2
colorama          0.4.4
isort             5.6.4
lazy-object-proxy 1.4.3
mccabe            0.6.1
paho-mqtt         1.5.1
pip               20.3.3
pylint            2.6.0
PyQt5             5.15.2
PyQt5-sip         12.8.1
setuptools        49.2.1
six               1.15.0
toml              0.10.2
wheel             0.36.2
wrapt             1.12.1
```

How to reproduce : Run `./tdmgr.py` from git-bash command line (with venv activated)

Result : Error as below, main GUI window frozen, most devices show "Fetching template name" in the "Module" column

```
$ ./tdmgr.py
Exception in thread Thread-1:
Traceback (most recent call last):
  File "C:\Users\Jean-Michel\AppData\Local\Programs\Python\Python38\lib\threading.py", line 932, in _bootstrap_inner
    self.run()
  File "C:\Users\Jean-Michel\AppData\Local\Programs\Python\Python38\lib\threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "D:\Projets\repos.local\tdm\venv\lib\site-packages\paho\mqtt\client.py", line 3452, in _thread_main
    self.loop_forever(retry_first_connection=True)
  File "D:\Projets\repos.local\tdm\venv\lib\site-packages\paho\mqtt\client.py", line 1779, in loop_forever
    rc = self.loop(timeout, max_packets)
  File "D:\Projets\repos.local\tdm\venv\lib\site-packages\paho\mqtt\client.py", line 1181, in loop
    rc = self.loop_read(max_packets)
  File "D:\Projets\repos.local\tdm\venv\lib\site-packages\paho\mqtt\client.py", line 1572, in loop_read
    rc = self._packet_read()
  File "D:\Projets\repos.local\tdm\venv\lib\site-packages\paho\mqtt\client.py", line 2310, in _packet_read
    rc = self._packet_handle()
  File "D:\Projets\repos.local\tdm\venv\lib\site-packages\paho\mqtt\client.py", line 2936, in _packet_handle
    return self._handle_publish()
  File "D:\Projets\repos.local\tdm\venv\lib\site-packages\paho\mqtt\client.py", line 3216, in _handle_publish
    self._handle_on_message(message)
  File "D:\Projets\repos.local\tdm\venv\lib\site-packages\paho\mqtt\client.py", line 3444, in _handle_on_message
    self.on_message(self, self._userdata, message)
  File "D:\Projets\repos.local\tdm\Util\mqtt.py", line 147, in on_message
    mstr = msg.payload.decode("utf8")
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xc3 in position 174: invalid continuation byte
```

When running in VScode debugger, the `msg.mayload` string was corrupted with erroneous bytes and mixup of 2 MQTT payloads.

When running the precompiled Windows EXE, no crash but the initial setup seems to take more time than before (purely subjective).

May be something wrong version with one of the packages I'm using ?

Let me know if you ned more details.

Thanks

**Comment by jziolkowski** [comment]
What happens when you run the same code but not inside git-bash?

**Comment by jziolkowski** [comment]
Either way, at best I can wrap that decode into a try..except with proper logging, but you will lose some data

**Comment by barbudor** [comment]
Morning Faz,

This morning I ran it from windows "DOS" prompt.
1st time it showed the problem on the 2nd device.
Then further runs where ok.
I switched back to git-bash and it ran 3 times without problems
Back in vscode it crashed the 1st run, not the 2nd but the 3rd...

I don't think it is a good idea to hide the problem with a try/catch unless other users reports the same.

What versions are you using the python & other packages ?

I feel it is timing / asynchronous related.
I'll investigate a little more.

Thanks

**Comment by Jason2866** [comment]
@barbudor I do not have this issue. Starting from VSC. Using Python 3.7.5 (64 bit) Not using a venv

**Comment by barbudor** [comment]
I tried with paho_mqtt==1.4 (instead of 1.5.1) but same
the corruptions in the payload seems to follow some kind of pattern
Always 4 bytes : `\xb4\x04\x00\x17`, `\xca\x04\x00\x17`, `\xb5\x04\x00\x18`

Fo now, I can't narrow down what in my environment (at large) can trigger that.
I will try to install Python 3.7.5 to see if it makes any difference

By the way the minimal PyQt is not 5.12 (as specified in setup.py). I think it should be bumped at least to 5.14.

**Comment by jziolkowski** [comment]
Well if 5.14 installs as the currently available version then fine. I only bump the requirement on purpose when there are new features added I use.

As for the MQTT issue: indeed that's something specific to your environment.

**Comment by jziolkowski** [comment]
I've checked these byte sequences with an online byte to ascii converter and all are malformed

**Comment by Jason2866** [comment]
@barbudor  You can try https://github.com/Jason2866/Portable_VSC_PlatformIO
Just download the needed stuff unpack and run. Nothing is installed or modified on your PC

**Comment by barbudor** [comment]
I've been able to get the same error in another python script running in parrallel and subscribing to all topics.
So it seems to be there at the broker level.


Regarding PyQt5, with installing 5.12 I get the following error when running tdmgr.py :
```
$ ./tdmgr.py
Traceback (most recent call last):
  File "./tdmgr.py", line 10, in <module>
    from PyQt5.QtCore import QTimer, pyqtSlot, QSettings, QDir, QSize, Qt, QDateTime, QUrl
ImportError: DLL load failed while importing QtCore: Le module sp▒cifi▒ est introuvable.
```
Upgrading to 5.13 solves the problem.
However this doesn't occur with 5.12 on my Ubuntu.
Could be a specific problem in the PyQt5 5.12 Windows package ? Missing DLL ?
I won't investigate this further, dosn't seem relevant.

**Comment by barbudor** [comment]
Something weird is occuring that is corrupting some MQTT messages but that's outside of TDM
Thanks

**Comment by jziolkowski** [comment]
> but that's outside of TDM

Of course, it's a stellar example of bug-free software :D

**Comment by jziolkowski** [comment]
Either way, I'll add logging of these messages b/c it shouldn't crash the app

**Comment by jziolkowski** [comment]
@barbudor please try this branch https://github.com/jziolkowski/tdm/tree/mqtt-decode-error
