### ISSUE TITLE
tdmgr very slow with short teleperiod and many devices

### ISSUE THREAD

**Issue by Bascht74** [jziolkowski/tdm#117]
Hi @jziolkowski , 

If you set the teleperiod in tasmota to a low setting, e.G. 10 (minimum allowed with Tasmota) the app gets almost unresponsive, if you got a couple of devices (I got 68). 
The app seems to be processing every tele data of every device, even that no window with the data it is open.

I am using tdmgr_0.2.8.exe with windows.

**Comment by jziolkowski** [comment]
Are you able to test the 0.3 dev version directly using python? 
I've rewritten how the parsing is done behind the scenes. 

Having this many devices is definitely an interesting benchmark as it clearly shows the bottlenecks otherwise invisible in small installations. If you could join TDM discord then we could even try doing some direct tests if you're interested.

**Comment by jziolkowski** [comment]
Also I'm thinking of writing a sort of tasmota mqtt chatter simulator for such benchmarks. Indeed interesting issue :)

**Comment by Bascht74** [comment]
@jziolkowski  Hi there, 

I had a hard time using the python app directly with python on windows, but I got it to work today. 
I assume that the 0.3 dev version ist https://github.com/jziolkowski/tdm with all the latest commits. I didn't find a 0.3 dev directy in your github account. Forgive me, if I didn't find it, maybe you could give me a hint.

I tried that version with 577a025 as latest commit. It is still a little bit slow, but much better. 
Before the app was unresponsive, but now, I can work with it!

Thanks for your work! Great!

**Comment by jziolkowski** [comment]
Dang indeed, branch 0.3 is local on my workstation still :facepalm: :joy: 
Either way, for the commit you are referencing. There's no difference in MQTT parsing between that, and what you have in 0.2.8 so TBH i'm surprised if you see improvements.

Let me prepare the 0.3 branch for commit so you can test.

**Comment by Bascht74** [comment]
Great!

**Comment by Bascht74** [comment]
@jziolkowski 
Hi there, can you upload the 0.3 branch?

**Comment by Bascht74** [comment]
@jziolkowski any news?

**Comment by jziolkowski** [comment]
Hey, sorry for keeping you watiting, I was busy. I'll try monday or tuesday

**Comment by Bascht74** [comment]
Any news? :-)

Am So., 17. Jan. 2021 um 12:49 Uhr schrieb Jacek Ziółkowski <
notifications@github.com>:

**Comment by Bascht74** [comment]
seems to work now...
