### ISSUE TITLE
updated docker version in docker hub

### ISSUE THREAD

**Issue by GiladShoham** [jziolkowski/tdm#120]
I've searched for this as a docker container, but only found a version that last published a year ago.
Having a docker version will really help many people I believe.
I would recommend just having a github action that auto-publish to docker hub upon new version.
I can help with this if required.

**Comment by jziolkowski** [comment]
Docker TDM is not something I'm interested in. If you want to maintain docker image of TDM and github actions related to it you're certainly free to do so, I do not.
