### ISSUE TITLE
Rules length not in line with latest Tasmota limits 

### ISSUE THREAD

**Issue by cluelesscris** [jziolkowski/tdm#121]
Rules can now be at least 1000 characters - TDM limits users to 480.

Since compression was added and improved the length of a rule set can be 'at least 1000 characters' - quoting from the Tasmota documentation.  

Can the limit in TDR be increased accordingly?

Thanks

**Comment by eku** [comment]
I ask to take into account that older versions have other limits and should still be supported.

**Comment by Jason2866** [comment]
Rules max size is not a fixed value anymore. It uses a compression algo (when needed) which has to be implemented in TDM.

**Comment by Jason2866** [comment]
Duplicate of #93
