### ISSUE TITLE
Non-responding interface on Big Sur

### ISSUE THREAD

**Issue by CMMenzel** [jziolkowski/tdm#123]
Hi there,
I am running into an issue where after first installation I can start TDM with `python3 tdmgr.py` and get to see the GUI, however I cannot operate any buttons nor use right click (the latter directly crashes the application).
Am I doing something wrong here or is this an issue related to OSX Big Sur?
Update to the latest python 3 (3.9.1) and have PyQt5 paho-mqtt with pip3 and pip installed.
Thanks
Chris

**Comment by CMMenzel** [comment]
This is the error it throws when I right click the GUI
`SB-532:tdm c.menzel$ python3 tdmgr.py
Traceback (most recent call last):
  File "/Users/c.menzel/scripts/tdm/GUI/Devices.py", line 315, in show_list_ctx_menu
    self.select_device(self.device_list.indexAt(at))
  File "/Users/c.menzel/scripts/tdm/GUI/Devices.py", line 323, in select_device
    relays = self.device.power()
AttributeError: 'NoneType' object has no attribute 'power'
Abort trap: 6`

**Comment by Jason2866** [comment]
Since we have no Apple devices we can not help. Added the help tag.

**Comment by jziolkowski** [comment]
Do you use anything custom in tasmota in regards to topics, fulltopics, prefixes, replies, etc?

**Comment by CMMenzel** [comment]
Not sure - does that qualify?
![image](https://user-images.githubusercontent.com/40633456/105905301-916e1f80-6022-11eb-9f1d-e524f78afd9d.png)

**Comment by jziolkowski** [comment]
ok, which mqtt broker are you using?

**Comment by lordbbk** [comment]
Hey, @CMMenzel,

This error is been thrown when you have not yet set the MQTT configuration, and/or your devices list is empty.
Please come back if this fixed your problem or not.

**Comment by CMMenzel** [comment]
Yes and no. I don't seem to be able to find any devices in the network. Hence I cannot say. You can close the issue though if that's the reason. Thank you!

**Comment by lordbbk** [comment]
@CMMenzel have you successfully connected TDM to the MQTT of yours?

**Comment by CMMenzel** [comment]
Yes, I can connect successfully but no device appears and no messages are intercepted.
<img width="1274" alt="Screenshot 2021-02-18 at 10 35 07" src="https://user-images.githubusercontent.com/40633456/108337080-06bdb200-71d5-11eb-8e70-a1691fc16dde.png">

**Comment by lordbbk** [comment]
> Yes and no. I don't seem to be able to find any devices in the network. Hence I cannot say. You can close the issue though if that's the reason. Thank you!

No, I was just asking because the crash itself is due to that list is empty.

Though, your real problem is not that crash, but that your list remains empty after you connected to the MQTT server. 

I suppose there are messages in MQTT which you could see e.g. with a mosquitto_sub, or any mqtt receiver after subscribing to all topics?

**Comment by CMMenzel** [comment]
That's correct - see attached screenshot
<img width="1438" alt="Screenshot 2021-02-18 at 11 17 33" src="https://user-images.githubusercontent.com/40633456/108342369-06c0b080-71db-11eb-870e-ce3e1ee8f3c8.png">

**Comment by jziolkowski** [comment]
If someone of you can please also test https://github.com/jziolkowski/tdm/tree/mac-menu-fix-test (but it requires running manually from .py file)

**Comment by Jason2866** [comment]
A compiled version with this change can be downloaded from here.
https://github.com/Jason2866/tdm/suites/2194664552/artifacts/45279114
If the App is not starting you have to change the rights with `chmod a+x tdmgr_0.2.9`

**Comment by Jason2866** [comment]
With the latest change from @jziolkowski the missing "MQTT settings" are there and TDM is working with MacOS Catalina
![image](https://user-images.githubusercontent.com/24528715/110234671-07bc4680-7f2c-11eb-9e3d-79108ad164db.png)

**Comment by CMMenzel** [comment]
Super, thank you @jziolkowski ! It is working fine for me too now on Big Sur!

**Comment by jziolkowski** [comment]
Lovely. I'll merge the change. Thanks for testing.

**Comment by Jason2866** [comment]
Compiled Mac App for download now in release section.
