### ISSUE TITLE
Added TLS Certificates and User Credentials to support ports 8883 and 443

### ISSUE THREAD

**Issue by homemations** [jziolkowski/tdm#129]
Tested with Amazon IOT Core and works fine to connect secure.  Also made changes to support not seeing disconnected devices icon on start up with Amazon.  Amazon does not support message retaining.  So had to not flag device as not connected when the LWT is undefined.  Instead device will look active, however the other data for the device will not be populated.  Tried to add an auto refresh as each device is loaded, but could not figure that out yet.  I tried to check into another branch but you have that blocked.  So I attached the files I modified.

[Broker.txt](https://github.com/jziolkowski/tdm/files/6093963/Broker.txt)
[mqtt.txt](https://github.com/jziolkowski/tdm/files/6093964/mqtt.txt)
[tdmgr.txt](https://github.com/jziolkowski/tdm/files/6093965/tdmgr.txt)

Change extension from txt to py

**Comment by jziolkowski** [comment]
Hi and thanks for this needed contribution.

Please make a fork in your repo, create a new branch there, and then make a PR with these changes. I'm not going to manually merge a file with such changes.

As for the lack of retain support on AWS IOT: that's a bummer, to be honest. However, I'm inclined to have TDM not remember any devices at all, and simply reload them on startup/reconnect. It limits a tiny bit of the functionality, but this way devices that are offline and/or have missing or invalid LWT will simply not appear.

**Comment by jziolkowski** [comment]
You don't need to hurry, as I probably will have sunday at the earliest to review the code

**Comment by homemations** [comment]
K.  Will do.  I might have changed some lines of code that did not need
changing.  So you can review closely on what lines you want to commit.

Also, I know that the 8883 using certificates work.  That is my use case
and I have it working.  But also added the 433 to leverage the username and
password credentials on AWS instead of certificates, but not sure that is
working using secure WEB sockets.

**Comment by okh-mzny** [comment]
I have created a Fork that implements these changes in 0.2.8 and then fast forwards to current 0.2.11

https://github.com/okh-mzny/tdm

So far I have encountered a couple of issues and was not able to connect.

- I was not able to specify 8884 as a port, it only started connecting after I changed to 8883. The code checks self.m_port == 8883 and only then connects with TLS.
- I do not get a prompt to decrypt my specified private key file, as such I have to decrypt it with openssl before use.
- I followed https://tasmota.github.io/docs/Self-signed-Mosquitto/ to set up my environment and so the client certificates I'm generating are all ec ones. I'm not sure wether the code can handle ec keys or only rsa ones.

As such TLS is still a WIP. I'm probably unqualified to work on this as I'm a total python and tls noob.

Still, I hope you can give me feedback and double check my fork to make sure I did everything correctly, I'm not too experienced in working with git either.

**Comment by vampywiz17** [comment]
@jziolkowski 

I saw that this feature already merged via https://github.com/jziolkowski/tdm/pull/164/commits

But if i download the master branch, can not found the settings in broker menu.

it is not added? ot how to use it?

**Comment by barbudor** [comment]
The pull request you are refering has not been merge as it was closed by its author on the day it was opened.

**Comment by vampywiz17** [comment]
@barbudor Ahh it is true... 

Well, i hope, that one time it will be avaliable. (it would be good) My smart home system run in the cloud, the ESP-s are running different places and connect it to MQTT with TLS and i would like to use this program to manage it via MQTT. Not to good idea to open a unencrypted mqtt port my cloud server....

**Comment by CyrilB1531** [comment]
Develop version should fix this issue. Could we close it?

**Comment by vampywiz17** [comment]
@CyrilB1531 

Working well with devel built!!
