### ISSUE TITLE
Problem displaying Zigbee Bridge

### ISSUE THREAD

**Issue by bwims** [jziolkowski/tdm#131]
I have a Sonoff Zigbee Bridge.  Although it connects ok and displays an RSSI of 90, the icon that displays signal strength at the beginning of the line show zero bars with a little red circle/white cross.

Curious!

**Comment by jziolkowski** [comment]
what happens when you right-click the device in question and select 'refresh'?

**Comment by Jason2866** [comment]
Can not reproduce. My Sonoff ZigbeeBridge appears as every other device

**Comment by bwims** [comment]
It's ok.  I upgraded Tasmota and the Zigbee firmware, which may or may not have solved the problem.  I also got the latest version of tdmgr, so I apologise for wasting time! 

Many thanks!

**Comment by jziolkowski** [comment]
Nah it's fine :)
