### ISSUE TITLE
Crash when right-clicking empty window

### ISSUE THREAD

**Issue by normanr** [jziolkowski/tdm#135]
If you right click when there are no devices listed:

```
Traceback (most recent call last):
  File "~/.local/lib/python3.8/site-packages/GUI/Devices.py", line 315, in show_list_ctx_menu
    self.select_device(self.device_list.indexAt(at))
  File "~/.local/lib/python3.8/site-packages/GUI/Devices.py", line 323, in select_device
    relays = self.device.power()
AttributeError: 'NoneType' object has no attribute 'power'
Aborted
```

**Comment by tbone2k-git** [comment]
Same for me! Is there any way to add devices in this case? I'm new to TDM.. 
I guess right clicking the empty area opens a context menu to add devices? Not sure, since TDM will just close. Mhh, thanks! o)

**Comment by barbudor** [comment]
You don't need to add devices to TDM
They are automatically discovered

**Comment by tbone2k-git** [comment]
Hey barbudor, it's you again! o)
Mhh.. ok, but I have 4 tasmota devices which can be accessed from "this" computer, why would TDM not show them?

**Comment by PVerburg** [comment]
TDM uses MQTT server to get all the information is your pc able to see and did you configure the mqqt tab

**Comment by tbone2k-git** [comment]
Ah, ok.. I got it! I was expecting auto discovery from network somehow. Thank you! o)

**Comment by jziolkowski** [comment]
after many many months I've gotten back to TDM development. This issue is fixed in latest develop branch, releases will follow within few next days with new features.

**Comment by tbone2k-git** [comment]
Thank you! o)
