### ISSUE TITLE
How to export?

### ISSUE THREAD

**Issue by bwims** [jziolkowski/tdm#136]
@balvant813 I've added the features you requested

_Originally posted by @jziolkowski in https://github.com/jziolkowski/tdm/issues/2#issuecomment-464510370_

One of the features was the ability to export a list of all devices, but I cannot see how to do it.

Is there a wiki that I've missed somewhere?

Thanks!

**Comment by bwims** [comment]
Hello?  Anyone there?

**Comment by barbudor** [comment]
Keep Cool @bwims 
If you are in a hurry, RTFC
There is an export function meant to create a CSV but it doesn't seem to be called from anywhere
As original requester didn't came back with feedback, this may have been removed as untested.

**Comment by bwims** [comment]
Thanks.  

Is enquiring after a week really a hurry? ( I've already experienced a project where a maintainer fell off the face of the Earth [alexa-remote2](https://github.com/586837r/node-red-contrib-alexa-remote2) , so I was worried that might have happened again.)

Presumably you mean RTF Code?  Tbh, since the statement was made that the facility was added, that didn't occur to me.  

Having looked, It seems all the code has been commented out, but I'd be happy to be a tester if  I could be pointed at a development version.

Hopefully @balvant813 will read this and respond.

**Comment by Jason2866** [comment]
The project creator/owner is still alive. As written in the readme there is no time for this at the moment.

**Comment by bwims** [comment]
Fair enough.  

You must admit that the statement that my enquiry was based upon led me to believe that the facility actually **_existed_**.


Back to plan A with node red interrogating each node as a reinvention of the wheel.  Ho Hum.  It does the job, but it's not as snazzy.

**Comment by bwims** [comment]
10 months on and another release and still no way to export the details.  

Can anyone confirm whether this is planned?  If not, there's no point telling me to fork it, I'm not up to the job.  But I will work harder on my clunky node red routines.

Thanks!

**Comment by Jason2866** [comment]
There is no time table. It is done when it is done.

**Comment by arovak** [comment]
@bwims I've made csv export work on my personal [fork](https://github.com/arovak/tdm).
By default it will output a csv with
`Device,IPAddress,Mac,Module,Version,Topic,CommandTopic,TeleTopic,StatTopic,FullTopic,Core`
If another sequence or fields would be needed you can add that in your `tdm.cfg` under the `[General]` section like this
`csv_export="Device;Module;Topic;Hostname;Version;IPAddress;SSId;BSSId;Channel;RSSI;RestartReason;Uptime"`

It works for my personal needs and if it works as expected for you I can make a PR.

**Comment by bwims** [comment]
Hi, that would be great! But - where is the executable?  I'm somewhat of a
Git noob.

Thanks!

**Comment by arovak** [comment]
I have no idea how to build an exe.

**Comment by bwims** [comment]
How did you test it then?  I use it on Windows 10, so I have no idea of how it runs under e.g. Linux.

Regardless, your description of the functionality sounds ideal to me.  If the main branch will accept your changes, I don't really need to test it.

Many thanks for your work!

**Comment by arovak** [comment]
I use Windows 10 too but I have python installed and start tdm with command prompt by going to the folder where tdm is cloned and run the command `python .\tdmgr.py`

**Comment by barbudor** [comment]
Theorically you should be able to build the exe by:
1) installing the needed requirements (pyinstaller) : `pip install -r requirements_build.txt`
2) run `pyinstaller.exe tdmgr.spec`

**Comment by arovak** [comment]
@barbudor thanks!

@bwims added the [exe ](https://github.com/arovak/tdm/releases/tag/0.2.11)for you to test. csv export button is added. 
![afbeelding](https://user-images.githubusercontent.com/56759291/153278441-b920930f-102b-487f-a0f7-1f4caa305097.png)

**Comment by barbudor** [comment]
But but but ... no icon !!! 🤣

**Comment by arovak** [comment]
it is in the 'non exe' version 😃 
![afbeelding](https://user-images.githubusercontent.com/56759291/153280927-76247354-2eeb-4843-868e-3fc1a311b0a1.png)

**Comment by bwims** [comment]
It works!

Many, many thanks!!  (Not worried about the icon! 😃)

B.
