### ISSUE TITLE
Unable to connect

### ISSUE THREAD

**Issue by titomontes** [jziolkowski/tdm#14]
Hello

I thought it was gonna be simpler to connect to my broker, but it seems that the current config does not work. With the same parameters (IP, port, user and pw) I´m able to connect from another MQTT client, no problems. 

Is there a special condition or another parameter that needs to be touched?

**Comment by jziolkowski** [comment]
no. no one reported any problems with MQTT connections so far.
do you have any specific configs?

in your user directory\TDM there is tdm.cfg, please paste its contents here (remove or change the password if it's sensitive)

**Comment by titomontes** [comment]
I´m sorry, I´m at a loss here. Maybe I´m just an idiot: I just downloaded the zip file, unzipped it and run it. There´s no cfg file or user directory, or I´m just plain enough that I can find it?

**Comment by jziolkowski** [comment]
user directory = your OS home directory for current user. On windows c:\users\your_login

**Comment by titomontes** [comment]
So sorry, I was looking elsewhere: 

```
[General]
hostname=192.168.1.10
port=1883
username=tito1
password=zambuca
connect_on_startup=true
window_geometry=@ByteArray(\x1\xd9\xd0\xcb\0\x3\0\0\0\0\0\a\0\0\0\0\0\0\x5\b\0\0\x3?\0\0\0\b\0\0\0\x1f\0\0\x5\a\0\0\x3>\0\0\0\0\0\0\0\0\x5V\0\0\0\b\0\0\0\x1f\0\0\x5\a\0\0\x3>)
splitter_state=@ByteArray(\0\0\0\xff\0\0\0\x1\0\0\0\x2\0\0\x3\x94\0\0\x1\x32\x1\xff\xff\xff\xff\x1\0\0\0\x1\0)
```

Cheers

**Comment by jziolkowski** [comment]
I assume you have paho-mqtt installed. Next, what it says on the status bar at the bottom after you click 'mqtt' connect button?

**Comment by titomontes** [comment]
Hello

![image](https://user-images.githubusercontent.com/3431396/53698505-ea54bf00-3ddd-11e9-8801-08637c06d660.png)

**Comment by jziolkowski** [comment]
so your error description is wrong :) you don connect, but the devices are not discovered automatically. 
Did you configure a different full_topic in tasmota?

**Comment by titomontes** [comment]
Oh crap, you just made me realize it (the no connecting problem). 

I don´t know if I did (guess I didn´t). Hope this clarifies it (from a Sonoff Dualr R2):

```
Program Version | 6.4.1.9 stb-1.1(sonoff)
-- | --
2019-02-19T21:43:53
2_4_2/2.2.1(cfd48f3)
0T06:33:25
218 at 0x3FA000
13
Power on
Persiana Mampara
Persiana Mampara
 
Montes01 (48%)
persianaA-5271
192.168.1.21
192.168.1.1
255.255.255.0
192.168.1.1
60:01:94:AD:B4:97
 
192.168.1.10
1883
tito1
DVES_ADB497
persianaA
sonoffs
salon/persianaA/cmnd/
cmnd/DVES_ADB497_fb/
 
None
Disabled
 
11383959
0x144051
1024kB
4096kB
549kB
2520kB
23kB
```

Cheers

**Comment by jziolkowski** [comment]
yes, your full topic is not default: `salon/persianaA/cmnd/`
and tasmota default is: `cmnd/some_device/` etc
In your case, you have to add each device by hand using the "Add" function
In this example, `topic` is "persianaA" and `fulltopic` is "salon/%topic%/%prefix%/"

![image](https://user-images.githubusercontent.com/11555742/53699268-b205ae80-3de6-11e9-8e87-352c39c79027.png)

In one of next commits I'll add a function to import devices from a CSV file.

**Comment by titomontes** [comment]
OK!!

That was a rookie mistake. From the first time I flashed a sonoff, I started changing everything, not knowing the consequences, hence, MQTT was a living hell for me.

I already set everything to stock, and TDM is working wonderfully.

Thanks a lot

**Comment by jziolkowski** [comment]
Glad to hear.
