### ISSUE TITLE
WebUI not opening in Windows 10

### ISSUE THREAD

**Issue by PedroGdiaz** [jziolkowski/tdm#144]
This is a very strange problem, on my PC I can not open WebUI, when I click on it the software crashes https://www.pegotec.net/screenshots/2021-05-24_18-52-14_2049.png
It works in my laptop but not in my PC, I have disabled windows defender, and no diference

**Comment by Jason2866** [comment]
Compiled TDM is tested on many Win10 PCs. Running well.
Something is wrong with your Windows 10

**Comment by PedroGdiaz** [comment]
Thanks for your feedback, I do understand and believe it is working great on all Windows. it is definitely a great tool to use. I was rather asking for help on advice on what could be the problem. 
Thanks in advance and a great tool you have developer!!!!

**Comment by barbudor** [comment]
@PedroGdiaz 
Are you using Web passwords on your tasmota devices ?
What exactly happens when you are trying to open the Web GUI ?
You say it crashes but from the screenshot it more looks like it becomes unresponsive.
Do you see any new tab opening in the GUI of TDM ?
Was it working before ?

**Comment by PedroGdiaz** [comment]
@barbudor 
Thanks for your kind questions, let me answer them below:
I do not use passwords for the WebUI
You are right it becomes unresponsive. basically, the title changes to (No responding), and I can not click or do anything, I have to close it from the task manager
No new tab is open.
It never worked on the PC but I always open it on the secondary monitor.

While doing more testing again to make detailed screenshots I had an idea, to open it on the main screen and not on the secondary monitor. And that is the issue. If I open the TDM in the secondary monitor it became unresponsive, if I open it on my Primary monitor it works.

I have the exact same issue with Cura 3d printer slicer.

In any case, this is for sure a solution for me. I do not mind opening it on the main monitor.

Thanks a lot, @barbudor for your questions. 
Thanks as well @Jason2866 for the great software.

I hope this may help someone in the future.

**Comment by Jason2866** [comment]
TDM is completely  written from @jziolkowski 
I only do some "side" work.
We are happy TDM is usefull for you.

**Comment by barbudor** [comment]
@PedroGdiaz 
I tried with the precompiled 0.2.10 on my 2nd screen, on a device without web-password and it opens as expected in the TDM window.

There's may be a problem with your graphic card driver setup

**Comment by PedroGdiaz** [comment]
@barbudor you are correct as I mention I also have problems with CURA, it has the same behavior.
@jziolkowski Thanks a lot for the great tool. You will receive a donation from me soon!
