### ISSUE TITLE
Button Settings Window doesn't set options in TDMgr 2.10

### ISSUE THREAD

**Issue by JoachimF** [jziolkowski/tdm#147]
On the Button Settings Window, when click on Save, option 13 is not send to the MQTT, didn't try other option,also TDMgr doesn't read values in the firmware.

Only SetOption32 and 40 are send

Thanks for this tools

Regards,

Joachim

**Comment by Jason2866** [comment]
Try v2.11

**Comment by jziolkowski** [comment]
Closing due to no feedback
