### ISSUE TITLE
Devices are not discovered if %topic% includes /

### ISSUE THREAD

**Issue by hausmeister42** [jziolkowski/tdm#148]
My MQTT Topic are structured like %topic% = Floorlevel/Room/Device and some experimental ones where %topic% = BLESensor
tdm 0.2.10 is only discovering devices which have no additional / in it.
This is maybe also related to issue #95
Example how the Topic is seen on not discovered  Device:
![image](https://user-images.githubusercontent.com/36170434/122300420-94997780-ceff-11eb-9d6e-30799a5bc736.png)
![image](https://user-images.githubusercontent.com/36170434/122300539-b8f55400-ceff-11eb-9fee-2619506100a5.png)

tx,

**Comment by jziolkowski** [comment]
It's not a bug. Read the project wiki here: https://github.com/jziolkowski/tdm/wiki/Autodiscovery

move the topic customization to fulltopic and it will work
