### ISSUE TITLE
tdmgr crashes

### ISSUE THREAD

**Issue by Schwenkner** [jziolkowski/tdm#149]
I could download it and start. It did running and working
Since I do have different topic and prefix configuration, I changed them. I'm not happy with prefix/topic order, I use it  the other way. Thus I had some problems with the subscription and I added some pattern.
Unfortunately I also have something like location/device as topic. Thus, subscription to something like domain/+/cmd/# does not work, since I need domain/+/+/cmd/#

Then I closed tdmgr and restarted it.
Now it opens and disappears immediately. Redownloading, coping it to a different folder didn't help.
How can I get it running again?

**Comment by barbudor** [comment]
Hi @Schwenkner 
What is your operating system and which installation option (1, 2, or 3) did you use ?

TDM has a configuration file `tdm.cfg` which should be located in folder `TDM` under your User folder (in Windows it is `c:\users\<yourname>\TDM`, same rule should apply to Linux and Mac)
In the configuration file in section `[General]` add the line:
```
loglevel=DEBUG
```
Delete any `tdm.log` file that may still be there
Try to run and post the log file here.

Please confirm your exact Tasmota's full topic(s) and how you configured TDM discovery topics.

**Comment by Schwenkner** [comment]
OS is Windows 10.
Id didn't do any "install", just started the file I've downloaded. It is the x64 version.^

Logfile is;
2021-06-19 14:06:56 [INFO] ### TDM START ###
2021-06-19 14:06:57 [INFO] MQTT: Subscribed to tele/#, stat/#, cmnd/#, +/tele/#, +/stat/#, +/cmnd/#, HAS/Neubarnim/guestroom/floorlamp/tele/#, HAS/Neubarnim/guestroom/floorlamp/stat/#, HAS/Neubarnim/guestroom/floorlamp/cmnd/#
2021-06-19 14:06:57 [INFO] DISCOVERY: LWT from an unknown device HAS/Neubarnim/guestroom/floorlamp/tele/LWT
2021-06-19 14:06:57 [DEBUG] DISCOVERY: Asking an unknown device for FullTopic at cmnd/Neubarnim/FullTopic
2021-06-19 14:06:57 [DEBUG] DISCOVERY: Asking an unknown device for FullTopic at HAS/cmnd/FullTopic


After I've got the hint here with the config file, I removed my pattern.
The pattern I've added was
[Patterns]
0=HAS/Neubarnim/guestroom/floorlamp/%prefix%/

Then after it is running at least.
As you can see, I removed %topic% from the pattern. May be this caused the crash.

My Fulltopic is HAS/Neubarnim/%topic%/%prefix%
As I told in my first post, my %topic% is always like "location/device". But since tdmgr only subscribes to "+" where the topic is specified, it cannot handle this, in my case it should be something like "+/+"

Do you have any suggestion for me how to solve this?
I know I can replace "location/device" by something like "location_device", but then I cannot subscribe to all devices in a given location.

**Comment by barbudor** [comment]
> OS is Windows 10.
> Id didn't do any "install", just started the file I've downloaded. It is the x64 version.^

So as per TDM [documentation](https://github.com/jziolkowski/tdm/wiki/Prerequisites-installation-and-running), you used Option 1. You probably didn't read it.

> My Fulltopic is HAS/Neubarnim/%topic%/%prefix%
> As I told in my first post, my %topic% is always like "location/device". But since tdmgr only subscribes to "+" where the topic is specified, it cannot handle this, in my case it should be something like "+/+"

This is wrong. As per Tasmota [documentation](https://tasmota.github.io/docs/MQTT/), `%topic%` should be a single word .
Tasmota could work with `%topic%` being multiple level but TDM assumes the rule is followed.
Other words (location) should go into your full topics.
It is perfectly legal to have different full topics across your various devices such as one device with:
```
MqttTopic floorlamp
FullTopic  HAS/Neubarnim/guestroom/%topic%/%prefix%/
```
and another one with
```
MqttTopic  floorlamp
FullTopic HAS/Neubarnim/mainroom/%topic%/%prefix%/
```

This is why TDM should be configured with your different full topics (from the GUI, you don't have to edit the config file for that)
```
HAS/Neubarnim/guestroom/%topic%/%prefix%/
HAS/Neubarnim/mainroom/%topic%/%prefix%/
```

**Comment by Schwenkner** [comment]
Thx for your kind explanation. I will give it a try and change my topics to be single word.
As a suggestion, it could be a configuration in tdm to substitute %topic% with one ore event more "+"wildcards.
Then it should be possible to use multiple words too.
