### ISSUE TITLE
Store preferences in ~/.config/

### ISSUE THREAD

**Issue by kylegordon** [jziolkowski/tdm#15]
Instead of creating preferences in ~/TDM/ and polluting the users home directory, it would be preferable to store it in a config location such as the commonly used ~/.config/

**Comment by jziolkowski** [comment]
This is related to QT library. Not all OSes use .config directory. The framework uses .config dir only if using native settings, but the same settings makes use of windows registry, which I reverted from. homePath() returned by the framework gives consistent file path and it will be used like that.
