### ISSUE TITLE
Updates over TDM 

### ISSUE THREAD

**Issue by thrusty66** [jziolkowski/tdm#150]
Is there a possibility to integrate a new function? A function with which you can send updates to the devices?
As a kind of batch processing. So that all devices can be selected with the same software and first receive "minimal" and then the correct update.

**Comment by Jason2866** [comment]
This is a standard function of Tasmota. Just provide the OTA url from the firmware you want
with TDM. Start the upgrade. Tasmota takes care of the rest what is needed

**Comment by barbudor** [comment]
As of today, TDM doesn't have a menu entry for `Upgrade`.
However the code is already here and just missing the handler to be added to the menu.
I tried to add it and it seems to work fine.

@jziolkowski Any reason why you don't enable the `Upgrade` menu ? That would be very useful.

**Comment by thrusty66** [comment]
I had only thought if you can select 5 devices, for example. Then select a loaded update and send it to these 5 devices.

**Comment by DaveMDS** [comment]
Pull request already there  ;-)
#139 

..but without multiple selection
