### ISSUE TITLE
Trojan:Script/Oneeva.A!ml in release tdmgr_0.2.11.zip

### ISSUE THREAD

**Issue by badabing2005** [jziolkowski/tdm#153]
Hi,

I tried to download tdmgr_0.2.11.zip from releases and Windows Defender reported a Trojan.
Trojan:Script/Oneeva.A!ml
https://www.microsoft.com/en-us/wdsi/threats/malware-encyclopedia-description?name=Trojan%3aScript%2fOneeva.A!ml&threatid=2147729349

It could be a false positive, however the severe nature of the trojan, I'm not taking any chances and reporting it here.

Incidentally the x86 version tdmgr_0.2.11_x86.zip does not report any issues.

**Comment by barbudor** [comment]
I just passed it through my local Kaspersky without any problem
VirusTotal multi-scanner do not report any infection neither

**Comment by badabing2005** [comment]
Thanks for the update,
Like I said, possibly a false positive.

I proceeded in setting up a linux based docker image to avoid any risks.
