### ISSUE TITLE
Auto discovery

### ISSUE THREAD

**Issue by ahmaddxb** [jziolkowski/tdm#157]
How can i get something like this to be found, have tried lots of combination and nothing works

![image](https://user-images.githubusercontent.com/43728586/126367082-24b76082-fa27-4f65-925d-a826b93bbed5.png)

If I change the topic from sonoff/garden_lights to garden_lights is it discovered

**Comment by barbudor** [comment]
Follow the rule: topic should be single word. 'sonoff' should in full topic like
Topic = garden_lights
Full topic = %prefix%/sonoff/%topic%

**Comment by jziolkowski** [comment]
Reading this usually helps https://github.com/jziolkowski/tdm/wiki/Autodiscovery

**Comment by ahmaddxb** [comment]
> 
> 
> Reading this usually helps https://github.com/jziolkowski/tdm/wiki/Autodiscovery

I have check it and it say to copy the full topic but as you can see attched the full topic is te default

**Comment by jziolkowski** [comment]
Look at the very end. It shows a similar example as yours.

**Comment by barbudor** [comment]
As I said your topic is wrong. It MUST be single level

**Comment by ahmaddxb** [comment]
> 
> 
> Follow the rule: topic should be single level. 'sonoff' should in full topic like
> Topic = garden_lights
> Full topic = %prefix%/sonoff/%topic%

Thanks that make sense, I missed your comment sorry

**Comment by ahmaddxb** [comment]
Ive been running like this for years never found an issue with it, didnt realise topic had to be single level.
