### ISSUE TITLE
[Request] Copy rules between devices

### ISSUE THREAD

**Issue by probonopd** [jziolkowski/tdm#162]
It wold be nice if one could copy one or all rules between devices.

Like this:

![image](https://user-images.githubusercontent.com/2480569/133001403-dfad2730-409d-4dd2-9130-3983fe06f712.png)

But "Copy Rules".

**Comment by jziolkowski** [comment]
Meanwhile I've added Load/save option to rules editor; you can achieve this using intermediate file(s)
