### ISSUE TITLE
[Request] Support CT (color temperature)

### ISSUE THREAD

**Issue by probonopd** [jziolkowski/tdm#163]
It would be nice if on devices that support it (= "2 channel lights") we would see something like

![image](https://user-images.githubusercontent.com/2480569/133001206-058c4525-6252-44a6-bef2-a513f35f2fe3.png)

instead of

![image](https://user-images.githubusercontent.com/2480569/133001222-6139d6c2-edc9-4327-830b-3f47588f9af7.png)

**Comment by probonopd** [comment]
Thank you very much @jziolkowski

**Comment by jziolkowski** [comment]
Don't mention it, only took 3 years :D
