### ISSUE TITLE
version  0.2.9-0.2.11 does not start on macOS High Sierra

### ISSUE THREAD

**Issue by stooky01** [jziolkowski/tdm#165]
tried to open the tdm on iMac running High Sierra
app bumps in the dock and the quits

**Comment by barbudor** [comment]
As advised on Discord, enable the logs

TDM has a configuration file tdm.cfg which should be located in folder TDM under your User folder (in Windows it is `c:\users\<yourname>\TDM`, same rule should apply to Linux and Mac)
In the configuration file in section [General] add the line:
```
loglevel=DEBUG
```
Delete any tdm.log file that may still be there
Try to run and post the log file here.

**Comment by Jason2866** [comment]
Try to start a second time.

**Comment by stooky01** [comment]
sorry guys for the late reply
I tried it again 0211 down to version 028 all the same
the icon bumps, and the app closes without any message or window just bumps and dissapears from dock
no tdm.cfg on the whole system no log no crash report nothing
bumps and dissapears

**Comment by Jason2866** [comment]
Sorry, we can not provide a compiled version for HighSierra since there is no Github Actions Environment for HighSierra. Build can only be done with MacOs 10.15 or newer.
