### ISSUE TITLE
Installation problem

### ISSUE THREAD

**Issue by SilentBob83** [jziolkowski/tdm#167]
Hello i get the following error:

 Could not find a version that satisfies the requirement tdmgr (from versions: )
No matching distribution found for tdmgr

how can i fix it ?

**Comment by SilentBob83** [comment]
Hello,

basically i have tried Option no. 2.

I use Linux raspberrypi 5.4.79-v7+ #1373 SMP Mon Nov 23 13:22:33 GMT 2020 armv7l

I get the repsonse: 
pip install tdmgr

Looking in indexes: https://pypi.org/simple, https://www.piwheels.org/simple
Collecting tdmgr
 Could not find a version that satisfies the requirement tdmgr (from versions: )
No matching distribution found for tdmgr


Maybe the Python Version is my problem.
Python  --version Returns 2.7.16
When I try to install Python3.6 the System tells me that i have already the latest Version installed 3.6.8-1.
Python3  --version Returns 3.7.3

I think now i understand that I have Python2 and Python3 installed. 
I read that i cannot just simply remove Python2.

I think i understand that i would Need to use pip3 install tdmgr but there i get the following Output:
sudo pip3 install tdmgr

Looking in indexes: https://pypi.org/simple, https://www.piwheels.org/simple
Collecting tdmgr
  Using cached https://files.pythonhosted.org/packages/27/a4/87c893b47f957f94499b20c55ef12f20f8bee3577d9c1d8eeb2dcf7716b5/tdmgr-0.2.11-py3-none-any.whl
Collecting PyQt5==5.14.2 (from tdmgr)
  Using cached https://files.pythonhosted.org/packages/4d/81/b9a66a28fb9a7bbeb60e266f06ebc4703e7e42b99e3609bf1b58ddd232b9/PyQt5-5.14.2.tar.gz
  Installing build dependencies ... done
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/usr/lib/python3.7/tokenize.py", line 447, in open
        buffer = _builtin_open(filename, 'rb')
    FileNotFoundError: [Errno 2] No such file or directory: '/tmp/pip-install-1nd5y5_v/PyQt5/setup.py'
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-install-1nd5y5_v/PyQt5/

I want to run the TDM on webui so I also tried to install PyQtWebEngine there i get the similar failure:

pip3 install PyQtWebEngine
Looking in indexes: https://pypi.org/simple, https://www.piwheels.org/simple
Collecting PyQtWebEngine
  Downloading https://files.pythonhosted.org/packages/fb/5d/4c5bb7adca4f2436545a391fe311dcb4ccc711f1ce2ab7adb87475ec566e/PyQtWebEngine-5.15.4.tar.gz (49kB)
    100% |████████████████████████████████| 51kB 1.2MB/s
  Installing build dependencies ... done
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/usr/lib/python3.7/tokenize.py", line 447, in open
        buffer = _builtin_open(filename, 'rb')
    FileNotFoundError: [Errno 2] No such file or directory: '/tmp/pip-install-avoq91y2/PyQtWebEngine/setup.py'

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-install-avoq91y2/PyQtWebEngine/

So what can i do ?

Best regards

Andreas


Gesendet von Mail für Windows

Von: Barbudor
Gesendet: Freitag, 15. Oktober 2021 17:29
An: jziolkowski/tdm
Cc: SilentBob83; Author
Betreff: Re: [jziolkowski/tdm] Installation problem (#167)

Sorry but our crystal ball being under maintenance, we have no way to guess which operating system you are using and which of the 3 installation method described in the wiki you are using.
May be if it's not too much to ask, you could give us more details ?
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by barbudor** [comment]
Seems that you can't get PyQT5 from PiPy on Raspian
You may have to install it using `sudo apt install python3-pyqt5`
But not sure it will install the right version for TDM, you have to use the python code directly by cloning the repo

**Comment by SilentBob83** [comment]
it seems not to be possible for me, thanks for your help
