### ISSUE TITLE
Only one BSSId alias works

### ISSUE THREAD

**Issue by Lenbok** [jziolkowski/tdm#168]
I've got several APs on my network and though the BSSId alias feature looked handy. The first entry I created worked, but when I added a bunch more, those subsequent aliases are never substituted into the WiFi BSSId column. The list of aliases is successfully being saved and persisted between sessions.

Using TDM 0.2.11.

**Comment by barbudor** [comment]
It's working fine for me with 4 BSSIds
Please check that you have not extra spaces or using a different byte separator

**Comment by Lenbok** [comment]
Hello @barbudor nice to see you again on another Tasmota related repo :-).

Thank you for confirmation that it works. I double checked and it turns out that my BSSId values were slightly out (I thought I could just paste the AP mac address shown in my UniFi controller UI, but it turns out the BSSId's are slightly different, e.g. a node with MAC address E0:63:DA:B6:3D:54 had a BSSId of E0:63:DA:B7:3D:54 and I had not noticed). I will close this report.

There is a different (minor) bug with the BSSId editing window though: If I edit the BSSId to correct the digit, then press save, when I re-open the BSSId aliases window, there are now two entries with that Alias name, once with the old BSSId, and once with the corrected BSSId. @jziolkowski is this worthy of a separate bug report?
