### ISSUE TITLE
Change MQTT Port

### ISSUE THREAD

**Issue by SilentBob83** [jziolkowski/tdm#169]
Hello it seems that it is not working to change the MQTT Port.
I have multiple MQTT Servers running with different ports.
If I change to default 1883 and change the device to the 1883 its working, but if I change both to 1885 it is not working. 
Can you please confirm this issue ?

**Comment by jziolkowski** [comment]
I just tried that and when I change port from the default 1883 then TDM doesn't connect, so it seems to be taking the port into account. I've checked the code and the port value from settings is indeed passed on to MQTT client.

**Comment by CyrilB1531** [comment]
Hello, 
With #199 version Merged in develop it is possible to change MQTT port. ie: 1883 for No SSL version and 8883 for SSL one. Could you please check if this issue is fixed with develop version?

**Comment by jziolkowski** [comment]
Solved with #199
