### ISSUE TITLE
Entering rules with backlog command is not working

### ISSUE THREAD

**Issue by herrfrei** [jziolkowski/tdm#17]
Entering a rule with `backlog` in the command part is not working since tasmote doesn't support nested backlogs. TDM uses a backlog command to send the rule plus it's settings. Please change this (separate rule transmission and rule settings).

Example rule set:

```
on System#Boot do 
  backlog MP3Volume 75;MP3Track 1 
endon 
on Wifi#Connected do 
  MP3Track 2 
endon 
on Wifi#Disconnected do 
  MP3Track 3 
endon 
on Mqtt#Connected do 
  MP3Track 4 
endon 
on Mqtt#Disconnected do 
  MP3Track 5 
endon
```

**Comment by jziolkowski** [comment]
Sorry it took so long. Issue fixed in upcoming 0.2
