### ISSUE TITLE
macintosh install

### ISSUE THREAD

**Issue by mac-city** [jziolkowski/tdm#18]
would anyone know how to install this on a mac?  i was able to install python 3.7, PyQt5, paho-mqtt, but get this error when trying to execute tdm.py....

$ cd '/Documents/home assistant/tdm-master/' && '/usr/bin/pythonw'  '/Documents/home assistant/tdm-master/tdm.py'  && echo Exit status: $? && exit 1
Traceback (most recent call last):
  File "/Documents/home assistant/tdm-master/tdm.py", line 3, in <module>
    from json import loads, JSONDecodeError
ImportError: cannot import name JSONDecodeError
MacBook-Pro:tdm-master$ 

thanks for any help

**Comment by jziolkowski** [comment]
Do you have any other python version installed? Try running tdm specifying `python3` as the command for python.

**Comment by nickidw** [comment]
I got it installed on Mac, used homebrew to install python3, then used pip3 to install dependencies.

If you use homebrew you might have to do the below:
`sudo mkdir /usr/local/Frameworks 

sudo chown `whoami` /usr/local/Frameworks`

**Comment by mac-city** [comment]
i don't use homebrew. just have it installed from the python website.  thanks for responding.  i have been messing around with learning python, just started, and i was able to run the debugger in vscode just now and got it to work.  it was dependencies that i thought i had installed, but just gave it another try and bingo!  thanks!

**Comment by andrethomas** [comment]
Closing this as it seems to be resolved
