### ISSUE TITLE
Missing icons for Save and Clear on Console

### ISSUE THREAD

**Issue by chrissv** [jziolkowski/tdm#181]
Using version 0.2.11 under Windows, but this has been the case for all versions I have every used.

When displaying the console, the icons for the Save and Clear commands are missing:
![image](https://user-images.githubusercontent.com/3324281/147900420-337163df-6f8e-4881-918a-49003a8d5ef2.png)

**Comment by barbudor** [comment]
Same for me
I even didn't knew there should be icons there
