### ISSUE TITLE
TDM-005 # Update sort for IP addresses

### ISSUE THREAD

**Issue by chelming** [jziolkowski/tdm#182]
When sorting IP addresses they sort as a string. That is, instead of .1, .2, .3, you get .1, .10, .11, .103, .2, .20, .224, .3.

Is there any way to have the sort work in a more logical sense? You'll notice that .10 comes before .6, and .67 comes before .7.
![image](https://user-images.githubusercontent.com/7746625/148800340-6a9e51f0-2963-4b11-9a1a-5fc8d98ac077.png)

**Comment by jziolkowski** [comment]
indeed it sorts by string, not by value. I'll have to think of a solution.
