### ISSUE TITLE
New TDM - SETOPTIONS

### ISSUE THREAD

**Issue by scargill** [jziolkowski/tdm#189]
Hi

I just downloaded the latest .EXE  0.2.11 version of TDM tonight and thought I'd take a look at the SETOPTIONS tab - TDM immediately crashed.

Pete.

**Comment by PVerburg** [comment]
What OS version win7 and win 10 here been using it for months here no problem ??

**Comment by dawnstrider** [comment]
**OS:** Windows 10, latest build
**TDM:** 0.2.11

Unable to reproduce

**Comment by scargill** [comment]
Windows 11 64 bit latest.

**Comment by jziolkowski** [comment]
A generic setoption editor widget won't be introduced now (and probably rather not soon) due to the fact that over the years some setoptions changed their function. I need to find a way to deal with it, but not high on prio list.
