### ISSUE TITLE
Info 'Minimal' durring upgrade process (11.0 -> 11.1)

### ISSUE THREAD

**Issue by jcbraem** [jziolkowski/tdm#192]
Hello,

Durring the upgrade from firmware 11.0 to 11.1 into 'Device' column I have not the information in red with 'Minimal' version.
This information is important to see if the upgrade is in process and finalized !

New issue with new firmware version?

**Comment by jziolkowski** [comment]
Not a TDM issue. Since tasmota uses compressed binaries for a long time now, in many cases using -minimal between upgrades isn't required.

**Comment by jcbraem** [comment]
In my case the minimal is used with TDM upgrade function ... and for twice of my device the upgrade is stoped with minimal version.
It not the first case and I make a second run of upgrade to finish. Before I see always 'Minimal' in red during the upgrade and it is cleared when the upgrade is complete.

In change log of 11.1 I see : 
" Shrunk tasmota-minimal.bin by removing all commands except Upgrade, Upload, OtaUrl, Seriallog, Weblog and Restart "
The TDM detection of 'Minimal' is provided by a firmware command ?

**Comment by jziolkowski** [comment]
are you manually setting the otaurl to include -minimum.bin?

**Comment by jcbraem** [comment]
No. Always the url for full stable official version in my language !

![2022-04-14_10-17-59](https://user-images.githubusercontent.com/103622420/163344682-6fd3c40e-3838-4f96-a6bc-ae4a6198356e.jpg)

**Comment by jziolkowski** [comment]
Then don't worry. Tasmota pulls the -minimal automatically if it needs to. If you don't see the 'minimal' tag in the column in TDM it doesn't mean that the update failed. And I haven't looked if the 11.x releases stopped reporting the minimal stage.

**Comment by jcbraem** [comment]
I don't worry :)
But your tools is very very userfull for the OTA upgrade for a lot of Tasmata devices (more of 20 !) and with the red tag 'Minimal' I have nerver need to check after a upgrade runned except if this tag is set. 
For the the day upgrade I have needed to check in all devices webpage ...

Thanks for your support !

**Comment by jcbraem** [comment]
Hello Jziolkowski,

Can't wait for the next update to see the change because with each change I have one or mores (but not many !) devices that go to 'minimum' and I have to go see in each device if it went well.

Thank you very much

Jean-Charles

**Comment by jcbraem** [comment]
Hello,
Sorry but with the last update I have always this issue -> Minimal version but not retrieve into TDM.
In the past this information is set in red label into TDM dashbord and it is very very practical !
Could you check if is it possible to retrieve this functionality ?
Thanks.
Jean-Charles
