### ISSUE TITLE
Export data and make IP URL link

### ISSUE THREAD

**Issue by balvant813** [jziolkowski/tdm#2]
Excellent utility..

It will helpful if we can  export data for ALL devices  (text or csv) including 'full topic' etc.

In GUI, if IPs are made url link to device, it will easy tp get to consule (to change rule etcs)

**Comment by Jason2866** [comment]
Just wait a little. It will be better 😆

**Comment by jziolkowski** [comment]
@balvant813 thank you for kind words.
a) it's doable.
b) I'll add a "Open WebUI" command to toolbar/context menu. Is that enough?

**Comment by jziolkowski** [comment]
@balvant813 I've added the features you requested

**Comment by balvant813** [comment]
That will be fine. Thanks

One of my Tasmota/Sonoff RF Brdige does not show any info in the Manager GUI (see below) – Only power icon is green! I tried ‘refresh’ from sub menu – stiff no info. I can reach the brisge via IP (see below).
Any ideas?

B Patel


[cid:image003.png@01D4C6DE.DA7A8950]

[cid:image004.png@01D4C6DE.DA7A8950]

**Comment by jziolkowski** [comment]
please send status 0 of this device

**Comment by balvant813** [comment]
1.
Just tried to use version 0.12 on Windows 10/Python 3.7.1

On ‘Export list’ It crashed with following error  messge:
Traceback (most recent call last):
  File "tdm2.py", line 530, in export
    self.device_model.mac(d),
AttributeError: 'TasmotaDevicesModel' object has no attribute 'mac'

2.  FYI
I always get follow messages on start up..
Warning: QT_DEVICE_PIXEL_RATIO is deprecated. Instead use:
   QT_AUTO_SCREEN_SCALE_FACTOR to enable platform plugin controlled per-screen factors.
   QT_SCREEN_SCALE_FACTORS to set per-screen factors.
   QT_SCALE_FACTOR to set the application global scale factor.
3. RF Bridge issue..
               It shows all info now.  Must be a device issue on my device!

Thanks for all work and help.

Balvant Patel

**Comment by jziolkowski** [comment]
Re: export: please check your pull. the mac() function is present in the current codebase.
Please verify if file "models.py" in Utils has it. Line #257

If it's not there, remove the whole directory and clone again from zero.

Regarding the QT messages; which version of PyQT you use?

Thanks for the feedback.

**Comment by bwims** [comment]
How do you export for all devices?  I can't see how that feature was implemented..

Thanks!
