### ISSUE TITLE
Enhancement:  run tdm.py using python3

### ISSUE THREAD

**Issue by ptrooms** [jziolkowski/tdm#20]
Just an/optional enhancement for the read.me.
At start I couldn't get the GUI active due to (let's assume) ignorance.

To have this wonderful code running on my Ubuntu 16.04 standard python intallation, I had to 
1) install python3:  sudo apt install python3-pip
2) install PyQt5 in Python3: pip3 install PyQt5
3) install mqtt in Python3: pip3 install paho-mqtt 
4) run the GUI using: python3 tdm.py 

So, no problem with the code but merely the execution which does not succeed (with me), running standard python 2.7, I had to use python 3.5.2 (standard ubuntu base install)

**Comment by Jason2866** [comment]
See https://github.com/jziolkowski/tdm#requirements

**Comment by jziolkowski** [comment]
@ptrooms I agree that it would be beneficial to clarify further. Many systems still have mixed python environments, so I'll update the documentation accordingly.
