### ISSUE TITLE
Tiny menu-items

### ISSUE THREAD

**Issue by crispy78** [jziolkowski/tdm#202]
My Windows-laptop has a resolution of 2880 x 1800 text and other items are scaled 200% as recommended, but TDMGR 2.11 show tiny menu-items.
![image](https://user-images.githubusercontent.com/42983001/184109424-d7403fc7-b173-4ab8-8890-260398e1e2b9.png)

**Comment by jziolkowski** [comment]
Got any feedback on this?

**Comment by crispy78** [comment]
Sorry for the delayed response, I've just downloaded the latest release and it seems to be working fine. Thanks.

**Comment by jziolkowski** [comment]
Thanks for the reply. However the issue is not gone, every now and then I see the same problem. I can't find a definitive path to reproduce it.
