### ISSUE TITLE
Device Tab not displayed correctly on macOS Mojave 10.14.4

### ISSUE THREAD

**Issue by DominikPalo** [jziolkowski/tdm#23]
As you can see on the attached screenshot, "Device Tab" is not displayed correctly.
TDM version: 0.1.20
OS version: macOS Mojave 10.14.4

![image](https://user-images.githubusercontent.com/1623257/57200549-d4a27800-6f8d-11e9-80a2-31512baa91d0.png)

**Comment by jziolkowski** [comment]
Whoa.

Unfortunately, I don't have anything Apple, so can't test it myself. Also, I've heard from other Mac users that the app works with no problems. TBH don't really have an idea on  how to proceed.

**Comment by oori** [comment]
I experience the same on macOS Mojave, probably a QT issue.   I guess this can be simply solved bypassed by explicitly setting background color on this child window.

I don't know QT, so no PR,  but try in your [init](https://github.com/jziolkowski/tdm/blob/master/GUI/DeviceConfig.py#L15) or in the [action](https://github.com/jziolkowski/tdm/blob/2aae89dcab183b1e6829706f009ed35acca784d4/GUI/DevicesList.py#L246).  maybe something like: `dev_cfg.setStyleSheet("background-color:white;");`   (see [here](https://wiki.qt.io/How_to_Change_the_Background_Color_of_QWidget))

**Comment by jziolkowski** [comment]
Thank you, I'll look into it.

**Comment by home0815** [comment]
I have the same under macOS High Sierra 10.13.6. By inserting "self.setAutoFillBackground(True)" in line 20 of "DeviceConfig.py" I could solve the problem. However, I am not familiar with Python and Qt, so this can have unwanted side effects.

**Comment by Jason2866** [comment]
TDM 0.2. released, give it a try
