### ISSUE TITLE
TDM (windows) was okay but all of a sudden is now crashing and so slow that it is unusable

### ISSUE THREAD

**Issue by HB787** [jziolkowski/tdm#233]
First of all It is a very nice tool

Somehow it is crashing all of a sudden and it becomes unstable and so slow it is now unusable.
Tried all kind of settings (emulation etc) but it is not working anymore like it did. 

It is really a pity because the tool is exactly what you need for Tasmota devices.
Wish there was a working Docker version of this application.
Tried the python version under windows but that is not working.
Installed gigabytes of MS C++ stuff without success, also went back to the 2.11 version but also the same issues.

I am using windows 10 64-bit operating system, x64-based processor
8 GB memory.
Using TDM version: tdmgr_0.2.13.exe

I really hope there is new version coming that works.

**Comment by jziolkowski** [comment]
if you used 0.2.13 successfully, and suddenly it doesn't work okay, then I'm sorry but that's outside of my control.

You can try the latest develop build, but be aware it now stores config in a different place. 

However, in the latest develop version there is a change in where the config files are located

On Linux/Unix it's ~/.config/tdm, on Windows it's %appdata%\Roaming\tdm

You can download it here: https://github.com/jziolkowski/tdm/suites/10063390689/artifacts/489884387

**Comment by HB787** [comment]
Perfect Jacek,

This tool works well, I would like it on Android!!

Thanks a lot
Harry

⁣BlueMail voor Android downloaden ​

Op 13 jan. 2023 16:57, om 16:57, "Jacek Ziółkowski" ***@***.***> schreef:

**Comment by jziolkowski** [comment]
> This tool works well, I would like it on Android!!

So do I :D there are plenty cool ideas, but unfortunately only 24hrs a day ;)

However I tihnk someone tried making an android app that was talking with tasmota devices
