### ISSUE TITLE
Timer button crashed

### ISSUE THREAD

**Issue by tyeth** [jziolkowski/tdm#235]
The first couple of buttons are fine if clicked with no devices in the list, and the rest seem to crash, but ignoring that and assuming you have 1 or more devices in the list (I have 1 LilyGo T-DisplayS3 running latest dev build of tasmota) then the Timers button caused a crash.
The error was:
```
 Traceback (most recent call last):
  File "C:\dev\software\tasmota-TDM\tdm\GUI\devices.py", line 461, in configureTimers
    timers = TimersDialog(self.device)
  File "C:\dev\software\tasmota-TDM\tdm\GUI\dialogs\timers.py", line 53, in __init__
    self.cbxTimerOut.addItems(self.device.power().keys())
TypeError: index 0 has type 'int' but 'str' is expected
```

Let me know how I can be more helpful. I'm running from git copy, using vscode and the espressif esp-idf environment setup (python etc in powershell). I've pip installed everything fine (although had to install mu-editor too to update and avoid version mismatch) and am launching with `python.exe tdpm.py`, or whatever it is, from within the integrated terminal and my default shell (esp-idf in powershell).

**Comment by Wyman42** [comment]
Idem for me. Installed on n windows 11
