### ISSUE TITLE
ESP info not showing right info.

### ISSUE THREAD

**Issue by SargonofAssyria** [jziolkowski/tdm#24]
![image](https://user-images.githubusercontent.com/24824113/58076227-fca6f380-7ba9-11e9-9ca3-9eff6bdb069d.png)

As you can see this tab is not showing info (n/a) although the info is present.
The module name ("OBI socket 2 (61)" and others) are also not present in the source.

**Comment by jziolkowski** [comment]
Thank you, but this is not a bug. These two values are available in WebUI because of the internall call, but not available via MQTT. Maybe they will one day if Theo implements these command.

**Comment by SargonofAssyria** [comment]
Oke, I will put it as a request there.
The module names are not up to the latest, perhaps that could be added.

**Comment by jziolkowski** [comment]
Yes, 0.2 is on the way with updates like that.

**Comment by SargonofAssyria** [comment]
Tnx.

**Comment by SargonofAssyria** [comment]
"ProgramSize" is there is STATUS4 (no space)

**Comment by jziolkowski** [comment]
Indeed. Tho, still no ChipID.
