### ISSUE TITLE
Crashes on Xubuntu Linux  5.15.0-70-generic #77-Ubuntu

### ISSUE THREAD

**Issue by jimford-sudo** [jziolkowski/tdm#240]
jim@zoostorm:~$ tdmgr.py 
Traceback (most recent call last):
  File "/home/jim/.local/pipx/venvs/tdmgr/lib/python3.10/site-packages/Util/models.py", line 281, in paint
    p.drawPixmap(option.rect.x() + 2, option.rect.y() + px_y, px.scaled(24, 24))
TypeError: arguments did not match any overloaded call:
  drawPixmap(self, QRectF, QPixmap, QRectF): argument 1 has unexpected type 'int'
  drawPixmap(self, QRect, QPixmap, QRect): argument 1 has unexpected type 'int'
  drawPixmap(self, Union[QPointF, QPoint], QPixmap): argument 1 has unexpected type 'int'
  drawPixmap(self, QPoint, QPixmap): argument 1 has unexpected type 'int'
  drawPixmap(self, QRect, QPixmap): argument 1 has unexpected type 'int'
  drawPixmap(self, int, int, QPixmap): argument 2 has unexpected type 'float'
  drawPixmap(self, int, int, int, int, QPixmap): argument 2 has unexpected type 'float'
  drawPixmap(self, int, int, int, int, QPixmap, int, int, int, int): argument 2 has unexpected type 'float'
  drawPixmap(self, int, int, QPixmap, int, int, int, int): argument 2 has unexpected type 'float'
  drawPixmap(self, Union[QPointF, QPoint], QPixmap, QRectF): argument 1 has unexpected type 'int'
  drawPixmap(self, QPoint, QPixmap, QRect): argument 1 has unexpected type 'int'
Aborted (core dumped)

tdm installed with <pipx  install tdmgr>

(Wish I knew enough to sort this out myself - but I'm too old now 8^(    )

**Comment by xinuxnt** [comment]
Same issue on Kali linux

**Comment by narc-Ontakac2** [comment]
Works on Debian bookworm.
