### ISSUE TITLE
Problematic requirement of tdmgr.py installation

### ISSUE THREAD

**Issue by ullix** [jziolkowski/tdm#245]
I installed tdmgr.py with `pip install tdmgr` and - while not yet understanding all of its functions - it does seem to work.

But I noticed that during install my existing `PyQt5 5.15.9` was replaced with `PyQt5-5.14.2`. But since I need 5.15.9 for another application, I reinstalled it.

When then testing tdmgr.py it did seem to work as before.

What is the situation: is 5.14.2 mandatory for tdmgr.py to work, or is 5.15.9 also ok?

**Comment by jziolkowski** [comment]
That's interesting. But yes, PyQt required by TDM is the minimum required version. If 5.15 is working as well i might bump the version for TDM.

Thanks for the info.

**Comment by jziolkowski** [comment]
Interesting. Can you please send me output of "timers" command from that device tasmota webui console?

**Comment by ullix** [comment]
This is the output of command `timers` given in the console on the website of device `NOUS A1T Tasmota`:

```
07:48:08.402 CMD: timers
07:48:08.423 MQT: geigerlog/stat/tasmotaGL1/RESULT = {"Timers":"ON","Timer1":{"Enable":1,"Mode":2,"Time":"01:00","Window":7,"Days":"1111111","Repeat":1,"Output":1,"Action":1},"Timer2":{"Enable":0,"Mode":0,"Time":"00:00","Window":0,"Days":"0000000","Repeat":0,"Output":1,"Action":0},"Timer3":{"Enable":0,"Mode":0,"Time":"00:00","Window":0,"Days":"0000000","Repeat":0,"Output":1,"Action":0},"Timer4":{"Enable":0,"Mode":0,"Time":"00:00","Window":0,"Days":"0000000","Repeat":0,"Output":1,"Action":0},"Timer5":{"Enable":0,"Mode":0,"Time":"00:00","Window":0,"Days":"0000000","Repeat":0,"Output":1,"Action":0},"Timer6":{"Enable":0,"Mode":0,"Time":"00:00","Window":0,"Days":"0000000","Repeat":0,"Output":1,"Action":0},"Timer7":{"Enable":0,"Mode":0,"Time":"00:00","Window":0,"Days":"0000000","Repeat":0,"Output":1,"Action":0},"Timer8":{"Enable":0,"Mode":0,"Time":"00:00","Window":0,"Days":"0000000","Repeat":0,"Output":1,"Action":0},"Timer9":{"Enable":0,"Mode":0,"Time":"00:00","Window":0,"Days":"0000000","Repeat":0,"Output":1,"Action":0},"Timer10":{"Enable":0,"Mode":0,"Time":"00:00","Window":0,"Days":"0000000","Repeat":0,"Output":1,"Action":0},"Timer11":{"Enable":0,"Mode":0,"Time":"00:00","Window":0,"Days":"0000000","Repeat":0,"Output":1,"Action":0},"Timer12":{"Enable":0,"Mode":0,"Time":"00:00","Window":0,"Days":"0000000","Repeat":0,"Output":1,"Action":0},"Timer13":{"Enable":0,"Mode":0,"Time":"00:00","Window":0,"Days":"0000000","Repeat":0,"Output":1,"Action":0},"Timer14":{"Enable":0,"Mode":0,"Time":"00:00","Window":0,"Days":"0000000","Repeat":0,"Output":1,"Action":0},"Timer15":{"Enable":0,"Mode":0,"Time":"00:00","Window":0,"Days":"0000000","Repeat":0,"Output":1,"Action":0},"Timer16":{"Enable":0,"Mode":0,"Time":"00:00","Window":0,"Days":"0000000","Repeat":0,"Output":1,"Action":0}}
```

**Comment by ullix** [comment]
'nother one with the same device:

```
$ tdmgr.py
{'NAME': 'NOUS A1T', 'GPIO': [32, 0, 0, 0, 2720, 2656, 0, 0, 2624, 320, 224, 0, 0, 0], 'FLAG': 0, 'BASE': 49}
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib/python3.9/threading.py", line 954, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.9/threading.py", line 892, in run

```

**Comment by jziolkowski** [comment]
> This is the output of command `timers` given in the console on the website of device `NOUS A1T Tasmota`:
> 
> ```
> 07:48:08.402 CMD: timers
> 07:48:08.423 MQT: geigerlog/stat/tasmotaGL1/RESULT = {"Timers":"ON","Timer1":{"Enable":1,"Mode":2,"Time":"01:00","Window":7,"Days":"1111111","Repeat":1,"Output":1,"Action":1},"Timer2":{"Enable":0,"Mode":0,"Time":"00:00","Window":0,"Days":"0000000","Repeat":0,"Output":1,"Action":0},"Timer3":{"Enable":0,"Mode":0,"Time":"00:00","Window":0,"Days":"0000000","Repeat":0,"Output":1,"Action":0},"Timer4":{"Enable":0,"Mode":0,"Time":"00:00","Window":0,"Days":"0000000","Repeat":0,"Output":1,"Action":0},"Timer5":{"Enable":0,"Mode":0,"Time":"00:00","Window":0,"Days":"0000000","Repeat":0,"Output":1,"Action":0},"Timer6":{"Enable":0,"Mode":0,"Time":"00:00","Window":0,"Days":"0000000","Repeat":0,"Output":1,"Action":0},"Timer7":{"Enable":0,"Mode":0,"Time":"00:00","Window":0,"Days":"0000000","Repeat":0,"Output":1,"Action":0},"Timer8":{"Enable":0,"Mode":0,"Time":"00:00","Window":0,"Days":"0000000","Repeat":0,"Output":1,"Action":0},"Timer9":{"Enable":0,"Mode":0,"Time":"00:00","Window":0,"Days":"0000000","Repeat":0,"Output":1,"Action":0},"Timer10":{"Enable":0,"Mode":0,"Time":"00:00","Window":0,"Days":"0000000","Repeat":0,"Output":1,"Action":0},"Timer11":{"Enable":0,"Mode":0,"Time":"00:00","Window":0,"Days":"0000000","Repeat":0,"Output":1,"Action":0},"Timer12":{"Enable":0,"Mode":0,"Time":"00:00","Window":0,"Days":"0000000","Repeat":0,"Output":1,"Action":0},"Timer13":{"Enable":0,"Mode":0,"Time":"00:00","Window":0,"Days":"0000000","Repeat":0,"Output":1,"Action":0},"Timer14":{"Enable":0,"Mode":0,"Time":"00:00","Window":0,"Days":"0000000","Repeat":0,"Output":1,"Action":0},"Timer15":{"Enable":0,"Mode":0,"Time":"00:00","Window":0,"Days":"0000000","Repeat":0,"Output":1,"Action":0},"Timer16":{"Enable":0,"Mode":0,"Time":"00:00","Window":0,"Days":"0000000","Repeat":0,"Output":1,"Action":0}}
> ```

I'm working on that. Please paste me the output of `status 7` command

**Comment by jziolkowski** [comment]
ok nvm, I found the issue. A small bug with variable unpacking. Fix pending soon.
