### ISSUE TITLE
Utilize XDG Base Directory Specification

### ISSUE THREAD

**Issue by rabin-io** [jziolkowski/tdm#264]
Can `TDM` be moved into `$XDG_CONFIG_HOME` folder? So that it doesn't pollute the home folder unnecessarily

If the environment is not set, is can default to `$HOME/.config`

ref: https://specifications.freedesktop.org/basedir-spec/basedir-spec-latest.html

**Comment by jziolkowski** [comment]
Yes, it's already done in development version. Release is pending.
