### ISSUE TITLE
TDM not running

### ISSUE THREAD

**Issue by Sawadee2u** [jziolkowski/tdm#27]
Hi, I have all the support programs install but get the following error when trying to start tdm.py.
Have not be able to get around this.
`pi@RDP-Heating:~/TDM $ python3.4 tdm.py

Traceback (most recent call last):
  File "tdm.py", line 9, in <module>
    from GUI import *
  File "/home/pi/TDM/GUI/__init__.py", line 7, in <module>
    from Util import DevMdl, CnsMdl
  File "/home/pi/TDM/Util/__init__.py", line 4, in <module>
    DevMdl = IntEnum('DevMdl', ["LWT", "TOPIC", "FULL_TOPIC", "FRIENDLY_NAME", "MODULE", "FIRMWARE", "CORE", "MAC", "IP", "SSID", "BSSID", "CHANNEL", "RSSI", "LINKCOUNT", "DOWNTIME", "UPTIME", "RESTART_REASON", "POWER", "LOADAVG", "TELEPERIOD", "MODULE_ID", "OTA_URL"], start=0)
TypeError: __call__() got an unexpected keyword argument 'start'
`
Can you help me with this? Thanks

**Comment by jziolkowski** [comment]
You're using Python3.4 where TDM requires 3.5 minimum (recommended 3.6 or 3.7)

**Comment by Sawadee2u** [comment]
Sorry, missed that. Will give it a try. Thanks
