### ISSUE TITLE
Sonoff 4ch pro r2 : only first relay acted appears

### ISSUE THREAD

**Issue by ThierryM** [jziolkowski/tdm#28]
Hi,
Thanks for your tool and the sharing.
I have a problem with a Sonoff 4ch pro r2 module and Tasmota 6.5.0 firmware. When I launch TDM, the 4 relays appear :
![Sélection_999(203)](https://user-images.githubusercontent.com/1470067/59728166-2d298e00-9239-11e9-8679-582713b501ce.png)
But when I activate one, the icon displayed changes and shows only 1 dot (green or red according the state of the relay acted). But I can change the state of the 4 relay and the dot shows only the state of the first relay acted (for instance the 4th relay if I changed it first).
If I quit the module line, I can only act on the same relay : impossible to chose belong the 4 relays : 
![Sélection_999(205)](https://user-images.githubusercontent.com/1470067/59728305-d5d7ed80-9239-11e9-952a-f7408d5c0297.png)
Regards,

Thierry

**Comment by jziolkowski** [comment]
Yes, I'm aware of this bug. If you can live without rules editor and telemetry for a while, get the development branch, where this bug is fixed.

**Comment by ThierryM** [comment]
Thanks for your answer.
For my use, the development branch seems to be enough. I think that I will use your tool to command the Sonoff 4ch Pro r2 behind a wifi range extender because the Sonoff GUI is not working.
Regards

**Comment by jziolkowski** [comment]
There are some undocumented new functions in the dev branch. For example in the device list after you select a device, F1 - F8 toggles the respective relay. Also double-click opens the device console with command completion. The command history is stored per-device. To access the command history push Ctrl+DownArrow for a list, Ctrl+E for last command, and Ctrl+H for history of other devices.

Thanks for the kind words ;)
