### ISSUE TITLE
In BSSid, crashes when entries are empty when deleting

### ISSUE THREAD

**Issue by jamman9000** [jziolkowski/tdm#29]
While poking around and figuring TDM out, I opened the BSSid window and clicked "Add", noticed a cell was created, selected it and pressed delete and python crashed with this error:

`Traceback (most recent call last):
  File "C:\users\jymorris\Google Drive\Property and Landlording\Home Automation\tdm-master\GUI\BSSID.py", line 60, in delete
    key = self.tw.item(self.idx.row(), 0).text()
AttributeError: 'NoneType' object has no attribute 'text'`

![image](https://user-images.githubusercontent.com/45108242/59792551-65b18200-92a2-11e9-854a-4ad47477f6a4.png)

It was reproducible so submitting here.

**Comment by jziolkowski** [comment]
Thank you, I'll add a check for this.

**Comment by Jason2866** [comment]
TDM 0.2 released. Give it a try
