### ISSUE TITLE
Error with TDM after changing firmware on device

### ISSUE THREAD

**Issue by mechromonger** [jziolkowski/tdm#3]
had an error come up after i ran the script a few times. windows 10 from command line now i cant get it to run at all. i did modify the firmware of a couple devices. not sure if thats related.

`Traceback (most recent call last):
  File "tdm.py", line 284, in mqtt_message
    payload = loads(msg)['StatusPRM']
  File "C:\Users\nekey\AppData\Local\Programs\Python\Python37\lib\json__init__.py", line 348, in loads
    return _default_decoder.decode(s)
  File "C:\Users\nekey\AppData\Local\Programs\Python\Python37\lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "C:\Users\nekey\AppData\Local\Programs\Python\Python37\lib\json\decoder.py", line 353, in raw_decode
    obj, end = self.scan_once(s, idx)
json.decoder.JSONDecodeError: Invalid control character at: line 1 column 113 (char 112)`

**Comment by jziolkowski** [comment]
Please paste here output of status 0 command so I can further investigate.

**Comment by mechromonger** [comment]
`06:52:37 CMD: status 0
06:52:37 MQT: esp02/stat/STATUS = {"Status":{"Module":18,"FriendlyName":["Garage Door","Sonoff2"],"Topic":"esp02","ButtonTopic":"0","Power":2,"PowerOnState":0,"LedState":1,"SaveData":1,"SaveState":1,"SwitchTopic":"garagestate","SwitchMode":[0,2,0,0,0,0,0,0],"ButtonRetain":0,"SwitchRetain":1,"SensorRetain":0,"PowerRetain":1}}
06:52:37 MQT: esp02/stat/STATUS1 = {"StatusPRM":{"Baudrate":115200,"GroupTopic":"sonoffs","OtaUrl":"http://192.168.1.114:9541/data/firmwares/sonoff.bin","RestartReason":"Software/System restart","Uptime":"0T18:31:44","StartupUTC":"2019-02-18T11:20:53","Sleep":50,"CfgHolder":4617,"BootCount":565,"SaveCount":1776,"SaveAddress":"FB000"}}
06:52:37 MQT: esp02/stat/STATUS2 = {"StatusFWR":{"Version":"6.4.1.17(83b950b-sonoff)","BuildDateTime":"2019-02-15T20:13:48","Boot":31,"Core":"2_5_0","SDK":"3.0.0-dev(c0f7b44)"}}
06:52:37 MQT: esp02/stat/STATUS3 = {"StatusLOG":{"SerialLog":2,"WebLog":2,"SysLog":0,"LogHost":"","LogPort":514,"SSId":["****,****"],"TelePeriod":300,"Resolution":"558180C0","SetOption":["000A80A9","280500000100000000000000000000000000","00000200"]}}
06:52:37 MQT: esp02/stat/STATUS4 = {"StatusMEM":{"ProgramSize":556,"Free":444,"Heap":19,"ProgramFlashSize":1024,"FlashSize":4096,"FlashChipId":"1625C2","FlashMode":3,"Features":["00000809","0FDAE794","000783A0","23B617CE","00003BC0"]}}
06:52:37 MQT: esp02/stat/STATUS5 = {"StatusNET":{"Hostname":"esp02","IPAddress":"192.168.1.115","Gateway":"192.168.1.1","Subnetmask":"255.255.255.0","DNSServer":"192.168.1.1","Mac":"DC:4F:22:1D:A0:D8","Webserver":2,"WifiConfig":4}}
06:52:37 MQT: esp02/stat/STATUS6 = {"StatusMQT":{"MqttHost":"192.168.1.110","MqttPort":1883,"MqttClientMask":"esp02","MqttClient":"esp02","MqttUser":"****","MqttType":1,"MAX_PACKET_SIZE":1000,"KEEPALIVE":15}}
06:52:37 MQT: esp02/stat/STATUS7 = {"StatusTIM":{"UTC":"Tue Feb 19 05:52:37 2019","Local":"Tue Feb 19 06:52:37 2019","StartDST":"Sun Mar 31 02:00:00 2019","EndDST":"Sun Oct 27 03:00:00 2019","Timezone":"+01:00","Sunrise":"07:51","Sunset":"18:16"}}
06:52:37 MQT: esp02/stat/STATUS10 = {"StatusSNS":{"Time":"2019-02-19T06:52:37","Switch2":"ON"}}
06:52:37 MQT: esp02/stat/STATUS11 = {"StatusSTS":{"Time":"2019-02-19T06:52:37","Uptime":"0T18:31:44","Vcc":2.960,"SleepMode":"Dynamic","Sleep":50,"LoadAvg":19,"POWER1":"OFF","POWER2":"ON","Wifi":{"AP":1,"SSId":"****","BSSId":"A0:AB:1B:ED:98:9C","Channel":1,"RSSI":76}}`

**Comment by jziolkowski** [comment]
It looks healthy.
Since you're on windows, please open the registry editor and go to the following key:
<pre>HKEY_CURRENT_USER\Software\Tasmota\TDM</pre> and delete the whole "Devices" key inside.
Make sure you pulled the latest commit and start again.

**Comment by jziolkowski** [comment]
Any update on this?

**Comment by mechromonger** [comment]
sorry about the delay. im still getting the same error after trying what you suggested.

**Comment by jziolkowski** [comment]
ok, please open tdm.py for editing, and localize this command:
<pre>payload = loads(msg)['StatusPRM']</pre>
before this line add this:
<pre>print(payload)</pre> (use spaces to indent code, not tabs)

**Comment by mechromonger** [comment]
ive tried that and im not getting anthing different to above. could you possibly post the correct position to place the print(payload) line. coding skills are sub par over here

`            elif found.reply == 'STATUS1':
                self.console_log(topic, "Received program information", msg)
                print(payload)
                payload = loads(msg)['StatusPRM']
                self.device_model.updateValue(found.index, DevMdl.RESTART_REASON, payload['RestartReason'])`

does this look right?

**Comment by mechromonger** [comment]
![py](https://user-images.githubusercontent.com/42733564/53316625-82ebca80-3918-11e9-84ad-50aee47c1d7f.PNG)

**Comment by jziolkowski** [comment]
ok then place it above 'self.console_log....'

**Comment by jziolkowski** [comment]
pull the newest commit, I'd added exception handling + error logging

**Comment by jziolkowski** [comment]
Closed due to inactivity.
