### ISSUE TITLE
When selecting Configure on MQTT discovered device, crashes with MQTT SetAuth error

### ISSUE THREAD

**Issue by jamman9000** [jziolkowski/tdm#30]
I setup the Broker information correctly and it connects successfully. Telemetry data is received from several devices, but when I select one and select Configure it creates a new tab for the device - says Connecting - and crashes with error. I have not configured admin credentials on my devices.

`Traceback (most recent call last):
  File "C:\users\jymorris\Google Drive\Property and Landlording\Home Automation\tdm-master\GUI\DeviceConfig.py", line 105, in setupMqtt
    self.mqtt.setAuth(self.settings.value('username'), self.settings.value('password'))
AttributeError: 'MqttClient' object has no attribute 'setAuth'`

![image](https://user-images.githubusercontent.com/45108242/59793047-9645eb80-92a3-11e9-9fef-8154365f7556.png)

**Comment by jziolkowski** [comment]
I'll look into it :)

**Comment by EvertDekker** [comment]
Same problem here

**Comment by cap60552** [comment]
I'm experiencing the same here.  The full error is:
`Traceback (most recent call last):
  File "C:\Tasmota Device Manager\GUI\DeviceConfig.py", line 105, in setupMqtt
    self.mqtt.setAuth(self.settings.value('username'), self.settings.value('password'))
AttributeError: 'MqttClient' object has no attribute 'setAuth'`

**Comment by EvertDekker** [comment]
Remark line 105 from DeviceConfig.py and give the 3 lines 107,108,109 an extra indent.
Works again (for me).
```
     if self.settings.value('username'):
            #self.mqtt.setAuth(self.settings.value('username'), self.settings.value('password'))

          self.mqtt.connected.connect(self.mqtt_subscribe)
          self.mqtt.messageSignal.connect(self.mqtt_message)
          self.mqtt.connectToHost()
```

**Comment by zeldaboch** [comment]
> Remark line 105 from DeviceConfig.py and give the 3 lines 107,108,109 an extra indent.
> Works again (for me).
> 
> ```
>      if self.settings.value('username'):
>             #self.mqtt.setAuth(self.settings.value('username'), self.settings.value('password'))
> 
>           self.mqtt.connected.connect(self.mqtt_subscribe)
>           self.mqtt.messageSignal.connect(self.mqtt_message)
>           self.mqtt.connectToHost()
> ```

This work for me and it didn't crush again opening Configure, but the Configure tab, now have all the settings "grayed".

**Comment by JoHaNMcR** [comment]
same problem can't configure anything

**Comment by jziolkowski** [comment]
Please try the dev branch. As of now it misses timers editor and telemetry preview, but the rules editor is working. I've rewritten how TDM talks with the devices, so your problem is no longer there.

**Comment by dhartsmith** [comment]
@jziolkowski This is a really helpful manager - your Dev branch is very nice - thanks!

**Comment by jziolkowski** [comment]
Thank you for the kind words. Keep up to date on dev branch, I try to keep adding stuff as often as I can now.
