### ISSUE TITLE
Tasmota Setup Automation

### ISSUE THREAD

**Issue by narc-Ontakac2** [jziolkowski/tdm#305]
As the number of Tasmota devices grows I am getting a bit tired of repeating the network setup again and again while the only piece of information that changes is the name I give to the device. Would be nice if TDM could help with that.

**Comment by jziolkowski** [comment]
You need to elaborate more, I'm not really clear what do you mean.

**Comment by narc-Ontakac2** [comment]
If I setup a new Tasmota device I connect to its WiFi and then use http://192.168.4.1 to enter about a dozen configuration entries (WiFi configuration, MQTT server and a few others). A configuration template that TDM enters would be nice.

**Comment by jziolkowski** [comment]
1) TDM works only over MQTT
2) TDM whould have to be able to access the private AP of that device, which means you would somehow need to connect your PC to that network.

A solution for your problems would be to compile your own image with all the network/MQTT data already input, and post-flashing only change the device name.

See the Tasmota docs about using TasmoCompiler, it's very user friendly for users that don't want to learn all the stuff needed to compile the entire image from scratch.

**Comment by narc-Ontakac2** [comment]
> 1. TDM works only over MQTT

I wasn't aware of that. It obviously kills the possibillty to implement what I want with reasonable effort.

**Comment by barbudor** [comment]
@narc-Ontakac2 
Why not hard coding your most basic settings (Wifi AP and MQTT ) into your own build firmware ? 
So when you flash a new device it is automatically up and running. You then just have to set specific configuration, wether through TDM or Web UI
