### ISSUE TITLE
Change default discovery path

### ISSUE THREAD

**Issue by EvertDekker** [jziolkowski/tdm#33]
Is it easy to change the **Auto Discovery protocol (%topic%/%prefix%/)**" path?
I need something in front of the auto discovery protocol _/vk/%topic%/%prefix%/_
Tried editing various files but no luck yet.

**Comment by jziolkowski** [comment]
If you can live without a complete rules editor and telemetryr preview, download the development branch from here. This functionality is implemented. I'll be glad to have someone else test it as well :)

**Comment by EvertDekker** [comment]
Can't get it working.
I try to find out in the code where the [Patterns] are read back from the tdm.cfg, but can't find it.

**Comment by jziolkowski** [comment]
https://github.com/jziolkowski/tdm/blob/development/tdm.py#L261:L273

**Comment by EvertDekker** [comment]
Thanks for your reply.
I'm a poor python programmer and still haven't my ide (pycharm) under control, so sorry for the stupid questions.
What I miss in tdm.py line 221 is the subscribing to custom patterns, I see that only will be subscribed to default topics for example **"+/stat/#"** instead of **"/vk/+/stat/#"**.
What do I miss?

**Comment by jziolkowski** [comment]
Oh, you're right. It seems I removed the actual subscriptions to the custom topics... I'll fix it tomorrow.

**Comment by jziolkowski** [comment]
@EvertDekker so I've rewritten how the application treats custom discovery topics and now it subscribes to them correctly. Check the latest dev commit.

**Comment by EvertDekker** [comment]
Tested it and it all works fine now with custom discovery topics.
Thanks.
