### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'replace'

### ISSUE THREAD

**Issue by mijnmodelbaan** [jziolkowski/tdm#35]
Hi,
Got tdm working; it's connecting to my mosquitto server. Tried to add a device manually as no device was detected automatically. Clicked 'Configure' to change '%topic%/%prefix%/' into '%prefix%/%topic%/' but while saving tdm crashed. Tried to start it again but it's giving me the error:

>Traceback (most recent call last):
>  File "tdm.py", line 236, in mqtt_connected
>    self.mqtt_subscribe()
>  File "tdm.py", line 248, in mqtt_subscribe
>    main_topics.append(self.device_model.commandTopic(idx))
>  File "D:\PlatformIO\Projects\HOMEAUT_folder\tdm\Util\models.py", line 221, in commandTopic
>    return self._devices[row][DevMdl.FULL_TOPIC].replace("%prefix%", "cmnd").replace("%topic%", self._devices[row][DevMdl.TOPIC])
>AttributeError: 'NoneType' object has no attribute 'replace'

and is crashing after displaying the main screen for a few seconds.
How to solve this?

**Comment by jziolkowski** [comment]
Hi.

Please use the development version. It's been largely rewritten and soon will be released as 0.2

**Comment by mijnmodelbaan** [comment]
Hi,

Tried the dev version. Could start it once, nothing was detected, the only thing I could do was disconnect the mqtt server but couldn't start it again (I think as there is no manual). 

So I closed the program and tried to start it again, but after a second it closed itself with the error:
>Traceback (most recent call last):
>  File "tdm.py", line 243, in mqtt_connected
>    self.mqtt_subscribe()
>  File "tdm.py", line 265, in mqtt_subscribe
>    self.mqtt.subscribe([(topic, 0) for topic in self.topics])
>  File "D:\PlatformIO\Projects\HOMEAUT_folder\tdm\Util\mqtt.py", line 134, in subscribe
>    self.m_client.subscribe(path)
>  File "C:\Users\wille\AppData\Local\Programs\Python\Python37\lib\site->packages\paho\mqtt\client.py", line 1311, in subscribe
>    raise ValueError('Invalid subscription filter.')
>ValueError: Invalid subscription filter.

So, how to solve this?

**Comment by jziolkowski** [comment]
please paste your tdm.cfg and devices.cfg files

**Comment by mijnmodelbaan** [comment]
Hi,

don't have devices.cfg, only tdm.cfg:

>[General]
>hostname=192.168.45.50
>port=1883
>username=xxx
>password=xxx
>connect_on_startup=true
>client_id=PVCJC1
>version=0.2.0
>window_geometry="@ByteArray(\x1\xd9\xd0\xcb\0\x3\0\0\xff\xff\xff\xff\xff\xff\xff\xf8\0\0\x6@\0\0\x3\\\0\0\x1,\0\0\0y\0\0\x5U\0\0\x2\xe2\0\0\0\0\x2\0\0\0\x6@\0\0\0\0\0\0\0\x17\0\0\x6?\0\0\x3[)"
>
>[Devices]
>
>[Patterns]
>0=TASMOTA/#/%prefix%/%topic%/
>1=TASMOTA/#/%topic%/%prefix%/

That's all in tdm.cfg (changed username and password}.

Should I change or remove anything?

**Comment by jziolkowski** [comment]
These patterns are bad. You should write there fulltopics EXACTLY as you have configured them in Tasmota. Do you have "TASMOTA/#/%prefix%/%topic%/" as fulltopic for your devices?

Remove these two lines and start over.

**Comment by jziolkowski** [comment]
My guess is you just need a "TASMOTA/%prefix%/%topic%/" as the pattern.

**Comment by mijnmodelbaan** [comment]
My topic is 'TASMOTA/%06X/' so TASMOTA followed by the device name.
My full topic is '%topic%/%prefix%/' so this will result in 'TASMOTA/<devname>/%prefix%/'.

![Annotation 2019-09-03 125207](https://user-images.githubusercontent.com/31405979/64167824-7eb1e400-ce4a-11e9-8cad-c0575823d470.png)

I removed the lines you mentioned and started over. The program is running, I added the line '%topic%/%prefix%/' in the pattern field but nothing is discovered at all.

![image](https://user-images.githubusercontent.com/31405979/64168519-03513200-ce4c-11e9-9157-1c38ae20f9bc.png)

Do I have to put some other settings in, somewhere? Or is it just not working this way w/o modification?

**Comment by jziolkowski** [comment]
Ahh, ok. Your tastmota settings are wrong. You don't add things like / to topic.

If you want to have tasmota devices not in the "root" of your mqtt, then add TASMOTA to the beginning of FullTopic. 

So, in Tasmota devices:
Topic = %06X
FullTopic = TASMOTA/%topic%/%prefix%/

In TDM, add this fulltopic pattern. It should work then.

**Comment by mijnmodelbaan** [comment]
Changed it like you said and after restarting tdm 2 devices were discovered. After another restart a 3rd device was discovered. So it's working but not flawlessly, some more work for you to do ;)

![image](https://user-images.githubusercontent.com/31405979/64170482-870d1d80-ce50-11e9-8932-272fad509ac5.png)

Found another small problem: the close button of the timer settings is not working. I open the settings, make no changes, push close w/o avail. Have to use the X.

But altogether it looks good. When will it be available in 'master'?

**Comment by jziolkowski** [comment]
Yes, there are still some bugs to hunt, I'm sure. Glad it works now.

Thanks for the tip about the button, must've overlooked action binding.

When? Great question. Soon (tm) :) Stay tuned.

**Comment by mijnmodelbaan** [comment]
I'll keep an eye on it. Thanks for the help!
