### ISSUE TITLE
Change: tele,cmd,state How to?

### ISSUE THREAD

**Issue by stefanbode** [jziolkowski/tdm#36]
Very nice project and I have different prefixes. Where to change this in the code?

**Comment by jziolkowski** [comment]
Argh, I was afraid someone would ask for this one day :) This function is not implemented yet. At this stage my focus is on the default Tasmota settings. Custom prefixes and values will come, but not now.

If ALL your devices use the same keywords, you might try modifying a few bits to see what happens.

1) https://github.com/jziolkowski/tdm/blob/development/Util/__init__.py#L27

2) https://github.com/jziolkowski/tdm/blob/development/Util/__init__.py#L108:L117
replace the prefixes with your values you added in step 1.

Granted, I have no way of testing this right now, 

BTW if you are a Discord user you can reach me on Tasmota Server under @Faziaty#6740 handle

**Comment by TrevisGordan** [comment]
I just checked out dev. 
It works if you add it to the default_patterns. - nice work on the dev branch looks nice.
I saw that you meanwhile already worked on a custom default pattern option.
I wanted to test it, so deleted the line now I get an index error. even after deleting the entire thing. Do you Save/cache settings locally somewhere?

**Comment by jziolkowski** [comment]
You mean patterns of prefixes? This issue is related to topic prefixes.

**Comment by TrevisGordan** [comment]
oh.. patterns. 
https://github.com/jziolkowski/tdm/blob/84d281ba6ebbe849c88c92ddfe07348fc5eec89c/Util/__init__.py#L28

**Comment by jziolkowski** [comment]
Please don't clutter other issues. Either open a new one, or visit the discord channel for TDM at https://discord.gg/eAhVDXM

**Comment by jziolkowski** [comment]
@stefanbode did your manual changing of prefixes work?

**Comment by stefanbode** [comment]
No did not work for me. maybe also a problem that my stat and tele is the same. My prefixes are
hm/setting
hm/status
hm/status

I gave up the end

**Comment by jziolkowski** [comment]
TDM 0.2 is released now, I will look into this problem of yours. Will keep you posted.

**Comment by stefanbode** [comment]
I changed it on both places to: setting/status/tele
```
  def cmnd_topic(self, command=""):
        if command:
            return "{}/{}".format(self.build_topic("setting"), command)
        return self.build_topic("setting")

    def stat_topic(self):
        return self.build_topic("status")

    def tele_topic(self):
        return self.build_topic("tele")

    def is_default(self):
        return self.p['FullTopic'] in ["%prefix%/%topic%/", "%topic%/%prefix%/"]
```

It crashed with the following error on MQTT connect. Works fine without the changes:
```
Traceback (most recent call last):
  File "C:\Users\stbode\Downloads\tdm-master (1)\tdm-master\tdm.py", line 320, in mqtt_message
    match = re.fullmatch(p.replace("%topic%", "(?P<topic>.*?)").replace("%prefix%", "(?P<prefix>.*?)") + ".*$", topic)
  File "C:\Users\stbode\AppData\Local\Programs\Python\Python37\lib\re.py", line 178, in fullmatch
    return _compile(pattern, flags).fullmatch(string)
  File "C:\Users\stbode\AppData\Local\Programs\Python\Python37\lib\re.py", line 286, in _compile
    p = sre_compile.compile(pattern, flags)
  File "C:\Users\stbode\AppData\Local\Programs\Python\Python37\lib\sre_compile.py", line 764, in compile
    p = sre_parse.parse(p, flags)
  Fi
le "C:\Users\stbode\AppData\Local\Programs\Python\Python37\lib\sre_parse.py", line 930, in parse
    p = _parse_sub(source, pattern, flags & SRE_FLAG_VERBOSE, 0)
  File "C:\Users\stbode\AppData\Local\Programs\Python\Python37\lib\sre_parse.py", line 426, in _parse_sub
    not nested and not items))
  File "C:\Users\stbode\AppData\Local\Programs\Python\Python37\lib\sre_parse.py", line 651, in _parse
    source.tell() - here + len(this))
re.error: nothing to repeat at position 0
```

any idea?

**Comment by stefanbode** [comment]
the incomming topic is:
`hm/status/ESP_083513/LWT`

**Comment by stefanbode** [comment]
Next step forward: looks like he find something but now interface hang on "Fetching module name" without success

```
LWT: hm/status/ESP_001F3E/LWT
Pattern: %prefix%/%topic%/
match: <re.Match object; span=(0, 24), match='hm/status/ESP_001F3E/LWT'>
possible_topic: status
Pattern: %topic%/%prefix%/
match: <re.Match object; span=(0, 24), match='hm/status/ESP_001F3E/LWT'>
possible_topic: hm
Pattern: hm/%prefix%/%topic%/
match: <re.Match object; span=(0, 24), match='hm/status/ESP_001F3E/LWT'>
possible_topic: ESP_001F3E
DISCOVERED status
```

**Comment by jziolkowski** [comment]
I can't test is right now, but did you also add correct fulltopic in the dialog?

**Comment by stefanbode** [comment]
In the AutoDiscovery pattern I have added: hm/%prefix%/%topic%/

**Comment by jziolkowski** [comment]
Ok, that's good.

Did you also change https://github.com/jziolkowski/tdm/blob/master/Util/__init__.py#L192 ?

**Comment by stefanbode** [comment]
yes this is also changed. I Expected:
```
Pattern: hm/%prefix%/%topic%/
match: <re.Match object; span=(0, 24), match='hm/status/ESP_001F3E/LWT'>
possible_topic: ESP_001F3E
DISCOVERED ESP_001F3E
```
but get DISCOVERED status

**Comment by stefanbode** [comment]
the Fulltopic on the device itself is the problem...

**Comment by stefanbode** [comment]
ok I got it working. I messed around how I defined the Fulltopic and the prefixes. Works fine but was wrong and your software recognized it. So great piece of work. Any idea why some devices create an exception is you refresh and request all these data? It looks like not all devices are affected. In the weblog you can see clearly that the different MQTT requests are responsible for the reboot.

**Comment by stefanbode** [comment]
my "wrong" devices report a wrong FullTopic. This causes the software to hang because it try to gather info from device "status" and this is not there.

**Comment by Jason2866** [comment]
Closed since the question is answered. Reopen if there is something left unanswered.
