### ISSUE TITLE
Clicking telemetry button second time crashes with atribute error

### ISSUE THREAD

**Issue by foxsam21** [jziolkowski/tdm#41]
This is consistent (for me). When I connect to mqtt host select a tasmota device and click telemetry it works fine. if I close the telemetry window and try to open it again, same or different device, it crashes with this error:
```
Traceback (most recent call last):
  File "/home/ottvio/venvs/tdm/tdm/GUI/Telemetry.py", line 85, in update_telemetry
    time_item.setText(1, time.replace("T", " "))
AttributeError: 'NoneType' object has no attribute 'replace'
Aborted (core dumped)
```
edit add ver.
 ```
python3 --version
Python 3.6.8
```

**Comment by jziolkowski** [comment]
Happens here as well, fix pending.
