### ISSUE TITLE
Prerequisites installation and running - errors 

### ISSUE THREAD

**Issue by pjchx** [jziolkowski/tdm#43]
windows string to install is missing the "PyQt5" at the end : 
now it says 
C:\<full path to python3 folder>\python.exe -m pip install 

it should say

C:\<full path to python3 folder>\python.exe -m pip install PyQt5

ALSO 
there is no mention about a need of mqtt-paho module being installed - probably worth mentioning it because without it pythonw.exe tdm.py will not run and will give no msg, only python.exe tdm.py would give a hint

thanks!

**Comment by jziolkowski** [comment]
You're right, I forgot about paho :P I'll fix it ASAP (or you can ;) )
