### ISSUE TITLE
No device detected

### ISSUE THREAD

**Issue by defconhaya** [jziolkowski/tdm#45]
Hi, 
My broker is RabbitMQ. TDM is successfully connecting to it but there is no device in list. All my tasmota devices are connected to this broker.
![devices](https://user-images.githubusercontent.com/186805/66255598-2d20b000-e78e-11e9-8b0d-89a2a8de278e.png)
![tasmota](https://user-images.githubusercontent.com/186805/66255616-63f6c600-e78e-11e9-8583-00d89be84ce6.png)

**Comment by jziolkowski** [comment]
Interesting why you have doubled subscribe topics. Also, do your devices use localized or customized payloads or prefixes?

**Comment by defconhaya** [comment]
Not always, now when I restart app there are no double subscribe topics but still no device in list:

![topics](https://user-images.githubusercontent.com/186805/66255685-4d9d3a00-e78f-11e9-90a5-f376ed3c08b7.png)

**Comment by jziolkowski** [comment]
Answer my other question plese as well

**Comment by defconhaya** [comment]
> 14:47:57 MQT: blitzwolf01/tele/SENSOR = {"Time":"2019-10-05T14:47:57","ENERGY":{"TotalStartTime":"2019-08-25T19:13:21","Total":14.967,"Yesterday":0.009,"Today":0.001,"Period":0,"Power":0,"ApparentPower":0,"ReactivePower":0,"Factor":0.00,"Voltage":234,"Current":0.000}}
![patterns](https://user-images.githubusercontent.com/186805/66255748-0cf1f080-e790-11e9-82a2-416a675990c3.png)

**Comment by jziolkowski** [comment]
The above pattern is wrong and unnecessary. However it might not a reason why it is not working.
How many devices you have, btw?

Also, when you get a mqtt client and connect to your broker's # topic, does it reply with retained LWT messages?

**Comment by defconhaya** [comment]
I have 6 tasmota devices. 
When I connect to # topic I get a ton of messages, how can I figure out if they are LWT ?

**Comment by jziolkowski** [comment]
because they will have LWT in topic. They should be visible at the beginning.
Here it looks like this:
![image](https://user-images.githubusercontent.com/11555742/66255971-b7b2e080-e789-11e9-85b9-8b3a8dc3de51.png)

**Comment by defconhaya** [comment]
No there are no LWT topics

**Comment by defconhaya** [comment]
Solved: I must restart a device in order to publish a LWT message.
Thanks for help !

**Comment by jziolkowski** [comment]
Well, not really. The LWT is a retained message, which is present in the broker and sent out whenever any client connects to it. As such, TDM upon connecting should trigger your MQTT broker to publish retained topics.
