### ISSUE TITLE
Device Exceptions with TLS during info gathering

### ISSUE THREAD

**Issue by stefanbode** [jziolkowski/tdm#47]
Hi, it looks like the firmware does not like it if request comming in too fast. I do see a reboot with an exception on many devices. Is it possible to insert some delay between the request? Honestly, some devices do not reboot and I have no idea why. I do not see a pattern.

**Comment by jziolkowski** [comment]
Then debug problematic devices. I've done stress testing of many devices over long time periods (issuing status 0 every second for half an hour) and LoadAvg increased by 1-2 max.

The batch of requests is sent only on TDM start. Later on, it mainly listens to MQTT and sends very little requests. Did you try upgrading the problematic devices to latest? What is the exception/restart reason?

**Comment by stefanbode** [comment]
Agree the issues happen on LWT online when different mqtt cmnd where send to the device. If it survives startup everything is ok

**Comment by stefanbode** [comment]
Updated all devices to STAGE core. Now it works.
