### ISSUE TITLE
Not wokring on Mac

### ISSUE THREAD

**Issue by MaxBec** [jziolkowski/tdm#50]
Followed the instructions but tool is not starting up on mac.

**Comment by jziolkowski** [comment]
I'm not a wizard, you need to post some error messages so I can see what the problem is.

**Comment by MaxBec** [comment]
Where are the log files located?

**Comment by jziolkowski** [comment]
When you start TDM from the console it should leave you a backtrack of the error

**Comment by MaxBec** [comment]
Nope it doesnt. There is just the python rocket hopping in the applications bar. And then it says its not reposnding anymore.

**Comment by jziolkowski** [comment]
Like I said, start the console, go to the TDM directory, and start it from there

**Comment by MaxBec** [comment]
Thats exactly what i am doing:
With python3 tdm.py

**Comment by jziolkowski** [comment]
and in the terminal it doesn't leave any error message?

**Comment by MaxBec** [comment]
Nope.

**Comment by MaxBec** [comment]
Do you have any idea how to fix this?

**Comment by jziolkowski** [comment]
Join our discord server. There are Mac users reporting TDM works. Since I don't have a Mac, I really can't help here.

**Comment by jziolkowski** [comment]
Closing as support has been provided on Discord
