### ISSUE TITLE
Incorrect info...

### ISSUE THREAD

**Issue by scargill** [jziolkowski/tdm#51]
TDM - very recent - just installed a few days ago... looking at my Sonoffs and other devices... lovely but...

![image](https://user-images.githubusercontent.com/1889411/68394694-3b376700-0166-11ea-9335-b056ff27f593.png)

It says that heating-cupboard-light (a sonoff) has been on for 539 days - WRONG - the cupboard didnt exist that long ago - and last December we had a new heating sytem installed, whole house power was off while that was happening. That light is using Sonoff-Tasmota 6.4.1 - well, it was until 5 minutes ago, then Iused OTA and it went up to 7.0.0.1 (completely automatically) - 5 minutes later I tried again and it went to 7.0.0.3 - this time I had to refresh the browser but it's working - stioll in light theme though....  I'm getting sidetracked, the MAIN issue is that erronious number of days.. I suess with it being old, not much we can do about it as long as the new version doesnt do the same - so instead, how do I fix that light theme?

**Comment by andrethomas** [comment]
Please post an image of your "Information" screen from the Tasmota WebUI.

**Comment by jziolkowski** [comment]
What Andre said, plus please paste the output of status 0 here. TDM doesn't do any calculation on its own, it simply presents the data received from the device, so let's see if the data sent from the device is correct.

**Comment by jziolkowski** [comment]
@scargill any progress on that?

**Comment by scargill** [comment]
Sorry - had too many other things... meanwhile moved to Tasmota 7.0.0.3 for all devices, not had the chance to check if that timing is out.. there are however no more ridiculous day counts.

**Comment by jziolkowski** [comment]
Ok, then I can close the issue as it's not reproducible.
