### ISSUE TITLE
Windows 10, crash during discovering devices

### ISSUE THREAD

**Issue by kmirny** [jziolkowski/tdm#52]
`C:\Python38-32\python.exe tdm.py`
`DISCOVERED X12`
`Traceback (most recent call last):`
`  File "C:\Users\konst\tdm\Util\models.py", line 92, in data`
`    if val.startswith("0T"):`
`AttributeError: 'int' object has no attribute 'startswith'`

The error is similar to #10. Discovered device X12 has Sonoff-Tasmota version 6.6.0.18 (Basic Module with BMP280 sensor).

**Comment by jziolkowski** [comment]
Please paste the result of `status 0`

**Comment by kmirny** [comment]
`22:00:30 CMD: status 0
22:00:30 MQT: stat/X12/STATUS = {"Status":{"Module":1,"FriendlyName":["Sonoff"],"Topic":"X12","ButtonTopic":"0","Power":0,"PowerOnState":3,"LedState":1,"LedMask":"FFFF","SaveData":1,"SaveState":1,"SwitchTopic":"0","SwitchMode":[0,0,0,0,0,0,0,0],"ButtonRetain":0,"SwitchRetain":0,"SensorRetain":0,"PowerRetain":0}}
22:00:30 MQT: stat/X12/STATUS1 = {"StatusPRM":{"Baudrate":115200,"GroupTopic":"sonoffs","OtaUrl":"http://thehackbox.org/tasmota/release/sonoff.bin","RestartReason":"Power on","Uptime":"22T06:19:06","StartupUTC":"2019-10-26T14:41:24","Sleep":250,"CfgHolder":4617,"BootCount":22,"SaveCount":98,"SaveAddress":"FB000"}}
22:00:30 MQT: stat/X12/STATUS2 = {"StatusFWR":{"Version":"6.6.0.18(sonoff)","BuildDateTime":"2019-10-20T17:16:30","Boot":7,"Core":"STAGE","SDK":"2.2.2-dev(38a443e)"}}
22:00:30 MQT: stat/X12/STATUS3 = {"StatusLOG":{"SerialLog":2,"WebLog":2,"MqttLog":0,"SysLog":0,"LogHost":"","LogPort":514,"SSId":["wildkhome_5g",""],"TelePeriod":300,"Resolution":"558180C0","SetOption":["00008009","2805C8000100060000005AFF000000000000","00000000"]}}
22:00:30 MQT: stat/X12/STATUS4 = {"StatusMEM":{"ProgramSize":560,"Free":440,"Heap":24,"ProgramFlashSize":1024,"FlashSize":1024,"FlashChipId":"144051","FlashMode":3,"Features":["00000809","8FDAE397","043683A0","22B617CD","01001BC0","00003081"],"Drivers":"1,2,3,4,5,6,7,8,9,10,12,16,18,19,20,21,22,24,26","Sensors":"1,2,3,4,5,6,7,8,9,10,14,15,17,18,20,22,26,34"}}
22:00:30 MQT: stat/X12/STATUS5 = {"StatusNET":{"Hostname":"X12-1506","IPAddress":"192.168.178.2","Gateway":"192.168.178.13","Subnetmask":"255.255.255.0","DNSServer":"192.168.178.13","Mac":"DC:4F:22:FA:C5:E2","Webserver":2,"WifiConfig":4}}
22:00:30 MQT: stat/X12/STATUS6 = {"StatusMQT":{"MqttHost":"192.168.178.13","MqttPort":1883,"MqttClientMask":"DVES_%06X","MqttClient":"DVES_FAC5E2","MqttUser":"openhabian","MqttCount":4,"MAX_PACKET_SIZE":1000,"KEEPALIVE":30}}
22:00:30 MQT: stat/X12/STATUS7 = {"StatusTIM":{"UTC":"Sun Nov 17 21:00:30 2019","Local":"Sun Nov 17 22:00:30 2019","StartDST":"Sun Mar 31 02:00:00 2019","EndDST":"Sun Oct 27 03:00:00 2019","Timezone":"+01:00","Sunrise":"08:02","Sunset":"17:08"}}
22:00:30 MQT: stat/X12/STATUS10 = {"StatusSNS":{"Time":"2019-11-17T22:00:30","BME280":{"Temperature":21.7,"Humidity":59.3,"Pressure":946.9},"PressureUnit":"hPa","TempUnit":"C"}}
22:00:30 MQT: stat/X12/STATUS11 = {"StatusSTS":{"Time":"2019-11-17T22:00:30","Uptime":"22T06:19:06","UptimeSec":1923546,"Heap":24,"SleepMode":"Dynamic","Sleep":250,"LoadAvg":5,"MqttCount":4,"POWER":"OFF","Wifi":{"AP":1,"SSId":XXXX","BSSId":"D8:50:E6:A8:20:E0","Channel":5,"RSSI":86,"LinkCount":1,"Downtime":"0T00:00:04"}}}`

**Comment by jziolkowski** [comment]
Check the latest commit please, I've added (again) a force conversion to str if the value is missing or malformed.

**Comment by kmirny** [comment]
thank you, now works!
