### ISSUE TITLE
All ON/All OFF sending wrong command 

### ISSUE THREAD

**Issue by Hajuskin** [jziolkowski/tdm#53]
Both actions send the power command with "true" or "false" as payload, but it should be 1 or 0 (or "on" or "off"). 

I fixed it for myself by changing "toggle_power_all" in Devices.py from

```
   self.mqtt.publish(self.device.cmnd_topic(r), str(not bool(idx)))
```
to
```
   self.mqtt.publish(self.device.cmnd_topic(r), idx ^ 1)
```

**Comment by jziolkowski** [comment]
This line has been fixed as well in my dev branch. Also, Tasmota now has a native "power all off" function, yet to be implemented in TDM.

Thanks for reminding anyway ;)
