### ISSUE TITLE
Feature Request: Add WebGUI to right mouse menu

### ISSUE THREAD

**Issue by arendst** [jziolkowski/tdm#55]
Selecting a device and clicking right mouse pops up a menu. 

Pls add option WebUi to it so I do not have to select the device and move the mouse all the way over to the top right option WebUI ;-)

**Comment by jziolkowski** [comment]
Can do. Also, Ctrl+U works :)

**Comment by arendst** [comment]
Ha.

How am I suppose to know the shortcuts.

**Comment by arendst** [comment]
Oops it's in the wiki.

**Comment by jziolkowski** [comment]
Already done, will be in next commit
![image](https://user-images.githubusercontent.com/11555742/69256553-ea8a2a00-0bb9-11ea-9f45-439d2bca7aa8.png)

**Comment by arendst** [comment]
You're faster than me!

Must be python over C++

**Comment by jziolkowski** [comment]
The beauty of QT, it's a fantastic framework.

**Comment by andrethomas** [comment]
Lets port Tasmota to python and make that run on the ESP's :)

**Comment by arendst** [comment]
Over to you: https://docs.micropython.org/en/latest/esp8266/tutorial/intro.html

**Comment by jziolkowski** [comment]
Hehe :) I actually tried writing something Tasmotish using MicroPython (I needed a simple power on/off over MQTT), but found Tasmota and here we are...

**Comment by jziolkowski** [comment]
Implemented.
