### ISSUE TITLE
Tamota version missing?

### ISSUE THREAD

**Issue by scargill** [jziolkowski/tdm#56]
Not so much an issue as a feature request of a plea  for help depending how it goes... hen watching TDM - its a handy way to see all your devices and update them. If next to the name ethey had the Tasmota version number (ie 7.0.0.5) that would make life a lot easier.

**Comment by jziolkowski** [comment]
It's already there, on the 'Firmware' view.
![image](https://user-images.githubusercontent.com/11555742/69274963-c3445480-0bdb-11ea-8990-c2cd573696f7.png)

If you want, you can modify the Home view to include this column, following this article from the wiki:
https://github.com/jziolkowski/tdm/wiki/View-mode-customization

**Comment by scargill** [comment]
So it IS.. Ignore me and thank you. Good job.
