### ISSUE TITLE
IndexError in Util\__init__.py.setoption()

### ISSUE THREAD

**Issue by segaura** [jziolkowski/tdm#57]
I tried for the first time tdm-0.2
I only specified my broker IP and connected
It discovered one of my tasmota and exited with this log

```
PS D:\Programmi\tasmota-device-manager-0.2> python tdm.py
DISCOVERED h801
Traceback (most recent call last):
  File "D:\Programmi\tasmota-device-manager-0.2\Util\models.py", line 104, in data
    return d.color()
  File "D:\Programmi\tasmota-device-manager-0.2\Util\__init__.py", line 295, in color
    68: self.setoption(68)
  File "D:\Programmi\tasmota-device-manager-0.2\Util\__init__.py", line 310, in setoption
    options = int(so[reg], 16)
IndexError: list index out of range
```

I managed to bypass this really dirty code editing, knowing nothing of what so, reg and o are in the code

```
        so = self.p.get('SetOption')
        if so:
            if reg in (0, 2):
			
                if len(so) <= reg:  # this one
                    return -1           # this other one
					
                options = int(so[reg], 16)   # this is 0.2 version original line 310
                if reg == 2:
                    o -= 50
                state = int(options >> o & 1)
```

hope this helps somehow (some exception handling will surely do, as well :-) )

...briefly looking at the current developement code my understanting is that the same problem can happen with it, also

```
        so = self.p.get('SetOption')
        if so:
            if reg in (0, 2, 3):
                options = int(so[reg], 16)
                if reg > 1:
                    o -= 50
                state = int(options >> o & 1)
```

**Comment by jziolkowski** [comment]
Your hack removed the problem by practically disabling what the function does :)

Please paste here output of `status 3` so I can test your setoptions here. Which Tasmota version you use?

**Comment by segaura** [comment]
Yeah, I know that was not a fix :-)

The only Tasmota detected was an old 5.1.2 or something like this, all the other are 6.7.1 and none were discovered, and still are not.

If "status 3" is a command I have to issue on the Tasmota console, sorry but that device has some issues now and is unreachable.

**Comment by jziolkowski** [comment]
TDM supports Tasmota versions 6.5+. If autodetection fails, check the 'Autodiscovery' page in TDM wiki.
