### ISSUE TITLE
Feature request - in the console - the line where you type in a command

### ISSUE THREAD

**Issue by scargill** [jziolkowski/tdm#60]
In the console - in the line where you key in a command (type the command and press ENTER to send) - unless I'm missing somethin there is no memory of past commands - so if for example you are messing with colours or something else that might take a few attempts, up arrow does not take you back up to previous lines....  any chance??

Pete

**Comment by jziolkowski** [comment]
Please read the wiki of this project, the shortcuts article.

**Comment by meingraham** [comment]
Pete - https://github.com/jziolkowski/tdm/wiki/Keyboard-shortcuts#console

**Comment by scargill** [comment]
Many thanks..
