### ISSUE TITLE
Feature request: Access via web browser

### ISSUE THREAD

**Issue by zampan0** [jziolkowski/tdm#62]
I have a bunch of ESP based devices (sensors and switches), many of them "tasmotized". 
It would be useful to manage them from remote (via tablet) and a web browser. 
Of course every device provides a web GUI, but having them all together like in this management tool would be aweful. The main "service" could run in background on a Raspi or similar, with a web GUI.

Just an idea ...

**Comment by Jason2866** [comment]
Duplicate see https://github.com/jziolkowski/tdm/issues/49#issuecomment-549609803
