### ISSUE TITLE
Modules disappear after some time?

### ISSUE THREAD

**Issue by GuybrushX** [jziolkowski/tdm#65]
I connected to my Home Assistant. 4 of 5 devices appeared and at some time there was also a Module detected. After some time all detected modules disappeared.

Also no idea why that 1 device is missing. SetOption19 is "1". Didn't investigate too much but looks like it's also missing in Home Assistant

**Comment by jziolkowski** [comment]
Again, if it's not a confirmed bug, please come to TDM Discord. Also if you observe devices disappearing in HA as well, then it sounds like a Tasmota misconfiguration, not a TDM issue.
