### ISSUE TITLE
Device list doesn't show devices with the same topic

### ISSUE THREAD

**Issue by jcalbert** [jziolkowski/tdm#67]
In fixing my network I found that TDM's device list doesn't allow multiple entries with the same topic.  Per https://tasmota.github.io/docs/#/MQTT?id=fallback-topic, it would we useful to index by `FallbackTopic` to make fixing topic collisions easier.

**Comment by jziolkowski** [comment]
I'm rewriting the way the devices are displayed and I'll try adding that feature.

**Comment by jziolkowski** [comment]
However, are you aware of all the implications of topics shared by a device? Is there a particular purpose for your setup?

**Comment by jcalbert** [comment]
Thanks.  In my case, I flashed a 4-pack of smart plugs to Tasmota in one go. Doing so gave them the same all a default topic of 'tasmota,'  I was trying to use TDM to change the topics, rather than the web UI.

**Comment by Jason2866** [comment]
@jcalbert  doing this could make it impossible to reach the devices via mqtt.
Reason for, mqtt broker will disconnect devices (because topic is used several times)
You should rethink the way how you initial setup your devices.

**Comment by andrethomas** [comment]
A workaround could be to power down all 4 so that none of them are connected and then power up one at a time and configure... rinse and repeat for the other 3.

**Comment by DonStefano** [comment]
> A workaround could be to power down all 4 so that none of them are connected and then power up one at a time and configure... rinse and repeat for the other 3.

That's also the way I'm introducing new devices. It will not be a feature with a high value to most of the users.

**Comment by jziolkowski** [comment]
I'm inclined to agree. Using non uniqure topics is against recommended tasmota practices.
After testing a few approaches I've decided to not pursue that functionality.
