### ISSUE TITLE
OSX-Crash

### ISSUE THREAD

**Issue by josemacaluso** [jziolkowski/tdm#68]
Hi, I'm running into a MAC (OSX) and I have a lot of devices (85), after configure the MQTT, the process start to recognise devices and crash with the following message:

>python3 tdmgr.py
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/Util/models.py", line 109, in data
    return d.color()
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/Util/__init__.py", line 322, in color
    68: self.setoption(68)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/Util/__init__.py", line 337, in setoption
    options = int(so[reg], 16)
IndexError: list index out of range

is the number of devices?
how can modify the mqtt configuration to not start with startup? config file?

thanks in advance
Mack

MAC OSX- Catalina
Python3

**Comment by jziolkowski** [comment]
What versions of Tasmota are you using?

**Comment by josemacaluso** [comment]
Many, 5.x, 6.x and 8.0

**Comment by jziolkowski** [comment]
5.x are unsupported in TDM and this is why it crashes. Of course I should add a exception in that case, but still.

**Comment by jziolkowski** [comment]
I'll add a fix later today, stay tuned.

**Comment by josemacaluso** [comment]
Hi, thanks for the new version, unfortunately it don't work, and crash anyway.

if there is some log that you want, or if you want to put some debugs to generate one, I'll be more than happy to run it for you and send you the logs.

The symptom is the same, it start, runs for a while and then crash.

Regards,
Mack

**Comment by jziolkowski** [comment]
If that's still relevant, please enable debug (as per project wiki) and post here. I will reopen the issue then.
