### ISSUE TITLE
Help needed - user instructions - Exception

### ISSUE THREAD

**Issue by Cloolalang** [jziolkowski/tdm#71]
This is a great product, thank-you for building this!
One question:
I could not find anywhere what "Exception" means in the friendly name window for one of my devices.
Can anyone point me to the instructions or tell what this means?
Cheers
P

**Comment by Jason2866** [comment]
See https://tasmota.github.io/docs/#/help/FAQ?id=device-resets-to-defaults-every-minute-or-so
for detailed info search for Esp8266 and exceptions
