### ISSUE TITLE
Timer config +- minutes GUI bug

### ISSUE THREAD

**Issue by tinamore** [jziolkowski/tdm#72]
Hi, when move to tab Timer GUI, i can not edit +- minutes for sunrise, Sunset, this is show time
![timer2](https://user-images.githubusercontent.com/2157845/71610830-fc061f00-2bc6-11ea-9aac-c847d7ba010b.jpg)

**Comment by jziolkowski** [comment]
Thank you, I'll look into it.

**Comment by tinamore** [comment]
Hi, can you add colum Index Increment device. Example:
![image](https://user-images.githubusercontent.com/2157845/71650292-7fe71500-2d47-11ea-8b3f-42570696333c.png)
Thanks

**Comment by tinamore** [comment]
Hi, can you add colum Index increment device. This will help to easily track the number of devices.
Example:
![image](https://user-images.githubusercontent.com/2157845/71650304-97be9900-2d47-11ea-8a16-e426ac965c97.png)
Thanks

**Comment by jziolkowski** [comment]
@tinamore please don't spam other issues with feature requests. 

I can add a summary with number of devices, but not per-row.
