### ISSUE TITLE
index out of range (Python 3 on Linux)

### ISSUE THREAD

**Issue by jchmielniak** [jziolkowski/tdm#73]
Hi,
I start tdmgr.py on Linux (Fedora 31) with broker configured. After connect it start collecting data and ends with error:

```
Traceback (most recent call last):
  File "/home/xx/Downloads/tdm-0.2.6/Util/models.py", line 109, in data
    return d.color()
  File "/home/xx/Downloads/tdm-0.2.6/Util/__init__.py", line 323, in color
    68: self.setoption(68)
  File "/home/xx/Downloads/tdm-0.2.6/Util/__init__.py", line 338, in setoption
    options = int(so[reg], 16)
IndexError: list index out of range
Aborted (core dumped)

```

**Comment by dajorad** [comment]
I am having the same issue with Windows and python 3.8

**Comment by linuskendall** [comment]
This seems to be an issue with older firmwares. I had one unit on 5.x and until I upgraded the firmware tdmgr kept on crashing with this error. You can also work around it by editing Util/__init__.py  and commenting out the lies in the color(..) function.

**Comment by Jason2866** [comment]
As in readme https://github.com/jziolkowski/tdm#minimum-fully-supported-tasmota-firmware-version-66017
