### ISSUE TITLE
Feature Request: Change console font

### ISSUE THREAD

**Issue by borpin** [jziolkowski/tdm#75]
The console font is very difficult to read (Win10 64bit). please make it configurable.

![image](https://user-images.githubusercontent.com/1322749/72293206-ebd05400-364a-11ea-9d7e-1f55ce3792e5.png)

BTW, excellent tool!

**Comment by jziolkowski** [comment]
In the next release, the app fonts will be embedded as resources, so it will look the same on each platform.
