### ISSUE TITLE
Power column doesn't show anything for Sonoff S26

### ISSUE THREAD

**Issue by eku** [jziolkowski/tdm#77]
As the subject says, TDM show neither power state nor power switching option for Sonoff S26. The devices uses the template for Sonoff S20.

Latest TDM is used together with ```mosquitto 1.6.8``` on Fedora 31.

**Comment by jziolkowski** [comment]
please paste output of `STATE` command

**Comment by eku** [comment]
I have removed some information for privacy reasons
```{..."Heap":25,"SleepMode":"Dynamic","Sleep":200,"LoadAvg":4,"MqttCount":2,"POWER1":"on","...}```

**Comment by jziolkowski** [comment]
I see your payloads are lower-case. As for now, it's unsupported. I'll fix it in next release.

**Comment by jziolkowski** [comment]
Can you verify that the power actions on the toolbar are not working?

**Comment by eku** [comment]
Sorry, but the power buttons in the upper left bar work. My mistake. But the power column shows nothing, as written in the initial post.

**Comment by Jason2866** [comment]
Please try latest version

**Comment by eku** [comment]
Same result with `0.2.8`.

**Comment by jziolkowski** [comment]
It's been ages but TDM is back in development.

Any update on this? Does the bug still appear?

**Comment by jziolkowski** [comment]
Closing due to no feedback
