### ISSUE TITLE
Installing tdm  error 

### ISSUE THREAD

**Issue by riker65** [jziolkowski/tdm#78]
Hi 
I am running into problems installing tdmgr.

pip is latest 

What am I missing?

Thanks T

`sudo pip install tdmgr
DEPRECATION: Python 2.7 reached the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 is no longer maintained. A future version of pip will drop support for Python 2.7. More details about Python 2 support in pip, can be found at https://pip.pypa.io/en/latest/development/release-process/#python-2-support
WARNING: The directory '/home/zwh100/.cache/pip' or its parent directory is not owned or is not writable by the current user. The cache has been disabled. Check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
ERROR: Could not find a version that satisfies the requirement tdmgr (from versions: none)
ERROR: No matching distribution found for tdmgr
`

`sudo pip  install --upgrade pip
DEPRECATION: Python 2.7 reached the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 is no longer maintained. A future version of pip will drop support for Python 2.7. More details about Python 2 support in pip, can be found at https://pip.pypa.io/en/latest/development/release-process/#python-2-support
WARNING: The directory '/home/zwh100/.cache/pip' or its parent directory is not owned or is not writable by the current user. The cache has been disabled. Check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
Requirement already up-to-date: pip in /usr/local/lib/python2.7/dist-packages (20.0.1)
`

mabye anyone having a more detailed guide?

thanks

**Comment by Jason2866** [comment]
Using old outdated not supported Python 2.7 version.
Use Python >= 3.6
