### ISSUE TITLE
devices couldnt be discovered across VLANs

### ISSUE THREAD

**Issue by beef76** [jziolkowski/tdm#79]
using the tasmota device manager in my main VLAN, the tasmota devices are in the smart home VLAN (different subnet which is not blocked by any firewall rules).
Connecting to the broker (which is also in this other smart home VLAN) is working fine, however no devices will be discovered and listed

**Comment by jziolkowski** [comment]
MQTT discovery is completely irrelevant of your IP/VLAN configuration. Please read the Autodiscovery article in this wiki project to see the requirements for it to work.

**Comment by beef76** [comment]
wooow that was fast, i just hit enter :-)
autodiscovery article has been followed and i turned also debug logging on to check for any issues. but without success and thats why i assumed it's the VLAN differency.

debug log is telling me:

2020-02-03 11:52:02 [INFO] ### TDM START ###
2020-02-03 11:52:03 [DEBUG] MQTT: Subscribed to tele/#, stat/#, cmnd/#, +/tele/#, +/stat/#, +/cmnd/#

But main window keeps staying empty and no devices are listed.
Actually 10 devices are configured in my sonoff adapter and 3 of them are actually active and plugged into power and are reachably by their IP address/webinterface.
Basic setup without any specialities, just gosund power plugs SP111 and SP1.

any other idea why the device manager is not able to list the devices?

**Comment by une18** [comment]
1) are your devices connected to the MQTT server? 
2)can you control them by MQTT? 
3)Is your computer connected to the same network where your devices are?

**Comment by beef76** [comment]
> 1. are your devices connected to the MQTT server?
>    2)can you control them by MQTT?
>    3)Is your computer connected to the same network where your devices are?

1-YES
2-YES
3-YES just different VLAN but can reach all devices and the MQTT Broker from this VLAN without any issues.

**Comment by beef76** [comment]
i'm sorry, was my fault! I'll close this one. Apologize guys

**Comment by jziolkowski** [comment]
Don't apologize ;) What was the error? So others can learn ;)

**Comment by beef76** [comment]
Human error ;-) seems the sonoff Adapter in IoBroker is not acting as a real mqtt Server like the mqtt Adapter. This one instead of the SONOFF Adapter made the device manager working ;-)



*** Sent from my mobile device ***
