### ISSUE TITLE
Problems starting tdmgr after installation

### ISSUE THREAD

**Issue by xury77** [jziolkowski/tdm#80]
Debian buster amd64, Python 3.7 installed

>  pip3 install tdmgr
> Collecting tdmgr
>   Using cached tdmgr-0.2.6-py3-none-any.whl (108 kB)
> Requirement already satisfied: PyQt5>=5.12 in /usr/local/lib/python3.7/dist-packages (from tdmgr) (5.14.1)
> Requirement already satisfied: paho-mqtt>=1.4 in /usr/local/lib/python3.7/dist-packages (from tdmgr) (1.5.0)
> Requirement already satisfied: PyQt5-sip<13,>=12.7 in /usr/local/lib/python3.7/dist-packages (from PyQt5>=5.12->tdmgr) (12.7.1)
> Installing collected packages: tdmgr
> Successfully installed tdmgr-0.2.6

After I can't start:

>  /usr/local/bin/tdmgr.py
> qt.qpa.plugin: Could not load the Qt platform plugin "xcb" in "" even though it was found.
> This application failed to start because no Qt platform plugin could be initialized. Reinstalling the application may fix this problem.
> 
> Available platform plugins are: eglfs, linuxfb, minimal, minimalegl, offscreen, vnc, wayland-egl, wayland, wayland-xcomposite-egl, wayland-xcomposite-glx, webgl, xcb.
> 
> Przerwane

Reinstalled few times. Still not able to start tdmgr

**Comment by jziolkowski** [comment]
This is your windows manager issue, not TDM. xcb plugin comes with your distro, not TDM nor even PyQt packages. I'm afraid I can't help you here. I'm not sure 100% but there was a similar issue, please search in the closed ones.

**Comment by xury77** [comment]
Yes you right. Problem is with my xserver and is trivial. :) I don't have any xserver installed. Moreover I tried starting tdmgr using Putty on ssh connection because I thought tdmgr is starting as a web service. Like as tasmoadmin. So very sorry for the confusion.
