### ISSUE TITLE
MQTT versions

### ISSUE THREAD

**Issue by hi-flyer** [jziolkowski/tdm#81]
I am trying to use nymead as the mqtt broker. it says that it only supports version 3.1.1. does tdmgr.py support mqtt version 3.1.1 and tdmgr.py will not connect to it.

tia

**Comment by jziolkowski** [comment]
TDM uses paho-mqtt under the hood. I'll check if it supports 3.1.1
However, I remember some users having issues with nymead. Something about retained messages not being sent out or something.

**Comment by hi-flyer** [comment]
I am coming to to conclusion that something is not right in tdmgr. I have mosquitto up and running. I have a tasmota outlet connected to mosquitto (verified by mosquitto log on tasmota restart shown below)
1581640825: Client c31b3dc3aa284200b4c7e226538a02f5 disconnected.
1581640831: New connection from 192.168.1.187 on port 1883.
when starting tdmgr, mosquitto log shows
1581640831: New client connected from 192.168.1.187 as c31b3dc3aa284200b4c7e226538a02f5 (c1, k30, u'a2e016a6e7a3448da4207493d4ba1fd3').
1581640914: New connection from 192.168.1.151 on port 1883.
Tasmota switch on 192.168.1.187  MQTT tab shows
Topic = %topic% (tasmota)
sonoff
Full Topic (%prefix%/%topic%/)
c31b3dc3aa284200b4c7e226538a02f5/%topic%/

I have added various versions of the %prefix%/%topic%/ to the autodiscovery options base on the tasmota MQTT tab
c31b3dc3aa284200b4c7e226538a02f5/%topic%/
/c31b3dc3aa284200b4c7e226538a02f5/%topic%/
c31b3dc3aa284200b4c7e226538a02f5/%prefix%/%topic%/
c31b3dc3aa284200b4c7e226538a02f5/%tasmota%/%topic%/
c31b3dc3aa284200b4c7e226538a02f5/%tasmota%/%sonoff%/
c31b3dc3aa284200b4c7e226538a02f5/%sonoff%/%topic%/
and disconnecting and reconnecting after these. and a number of others.
nothing shows up in tdmgr.
The installation is on ubuntu 18.04 on ip 192.168.1.151. the install of tdm was done as
pip3 install PyQt5 paho-mqtt
pip3 install tdm
so what is it that I am doing wrong that I see nothing on tdmgr

**Comment by jziolkowski** [comment]
Nothing wrong with TDM, you use Tasmota without %prefix% in fulltopic against tasmota recommendation, and not minding that TDM needs that part for autodiscovery, as it says in the docs.

**Comment by Jason2866** [comment]
The question has been answered
