### ISSUE TITLE
TDM crashes when fetching Module Names

### ISSUE THREAD

**Issue by schwerg** [jziolkowski/tdm#85]
Th application chrashes while "Fetching module name" with the error message:
`Traceback (most recent call last):
  File "tdmgr.py", line 375, in mqtt_message
    self.env.lwts.remove(d.tele_topic("LWT"))
ValueError: list.remove(x): x not in list`

**Comment by jziolkowski** [comment]
paste a few examples of topics/fulltopics of your devices. I suspect something non-standard going on

**Comment by mjf55** [comment]
I am having the same issue on the windows version, just launching the tdmgr_0.2.6.exe.  First time, I had to add my mqtt credentials, and after I pressed Connect, it crashed ( well in windows, it disappeared ).  Then in subsequent launches, disappears while fetching module names.  I have 3 tasmota devices.  The devRGBW is a wemos with tasmota, driving an RGB and a While LED string.  Here are the topics I use:

name: "Family Room Light"
    command_topic: "cmnd/FamRoomLight/power"
    state_topic: "stat/FamRoomLight/POWER"
name: "Sonoff Extension Cord"
    command_topic: "cmnd/sonoff_extension_cord/power"
    state_topic: "stat/sonoff_extension_cord/POWER"
name: "devRGBW-RGB"
    command_topic: "cmnd/devRGBW/power1"
    state_topic: "stat/devRGBW/POWER1"
name: "devRGBW-White"
    command_topic: "cmnd/devRGBW/power2"
    state_topic: "stat/devRGBW/POWER2"

**Comment by mjf55** [comment]
Just tried running it from the command prompt window same crash / disappearance .  No errors posted to the command prompt window.
