### ISSUE TITLE
Cannot discover devices with custom prefixes

### ISSUE THREAD

**Issue by dbahles** [jziolkowski/tdm#86]
I have change the prefix 1 & 2 for  camd and stat to a custom message "totas & "fromtas" I can no longer get the auto discover to find the devices.

I tried using the full message "topic and prefix" "sonoff/totas/"  but now the program crashes and will not start.

**Comment by jziolkowski** [comment]
custom prefixes are not yet supported.

**Comment by dbahles** [comment]
OK thank you - do you have a time frame?

**Comment by jziolkowski** [comment]
It is on the roadplan, but due to time constraints and RL issues I can't tell you any date. But you're not the first one to ask for this feature, so saty tuned.

**Comment by dbahles** [comment]
Thank you Jacek for the update

I really like your dashboard please keep up the great work

Dave

**Comment by ot3** [comment]
Any update on this feature request? Unfortunately the lack of this feature prevents me from using TDM. A simple manual edit of the .cfg file would be OK for me.
