### ISSUE TITLE
More than 8 Outputs visualized not correct

### ISSUE THREAD

**Issue by MichiM2** [jziolkowski/tdm#87]
When having a Tasmota-Device with only one Relais, only the Button "ALL on" ist displayed.

![image](https://user-images.githubusercontent.com/37748504/77851688-badbd600-71da-11ea-84a3-bcb806def7dc.png)

When having a Device with 2 Relais (eg Sonoff Dual) the "ALL on" Button is displayed and additionally two buttons for the two Outputs:

![image](https://user-images.githubusercontent.com/37748504/77851777-3047a680-71db-11ea-8a10-4ee9aa69be3a.png)

For a device with more than 8 Outputs (e.g. a Sonoff BASIC (1 Relais) with a PCF8574(8 Outputs) only the first 8 outputs are displayed.

![image](https://user-images.githubusercontent.com/37748504/77852001-85d08300-71dc-11ea-8231-9e66023f5bfd.png)

 Tasmota itself recognises the Outputs correct:

![image](https://user-images.githubusercontent.com/37748504/77852136-35a5f080-71dd-11ea-9cba-6edc0ec2d2ce.png)

TDM seems to know the correct number of outputs because it switches them all ON or OFF when pressing the "ALL on" or "All off" Button:

![image](https://user-images.githubusercontent.com/37748504/77852182-8584b780-71dd-11ea-98e5-2d8f72a00c6c.png)

**Comment by jziolkowski** [comment]
You are correct in all your assumptions. It shows max of 8 devices because no one used more in the past. The UI part for the relays is being rewritten a bit, so watch this space for an update "soon"
