### ISSUE TITLE
Can't open Web UI when device has a WebPassword

### ISSUE THREAD

**Issue by barbudor** [jziolkowski/tdm#91]
Hi

I have a `WebPassword` on my devices and open the Web UI in TDM fails saying the device is unreachable `ERR_TOO_MANY_RETRIES`

Is there a way to specify the `WebPassword` somewhere ?
Apologies if I missed the right configuration.

Alternatively, is it possible to open the UI in the default Web browser as password are stored there ?

Thanks for your useful and nice software.

Best regards

**Comment by 373137461** [comment]
#105 Please try if I solved your problem.Because I also showed up, I habitually set a password for the device😁

**Comment by barbudor** [comment]
Hi @373137461 
Thanks.
It only partially solve the issue :
1) Without entering username/password in the new fields of the Settings dialog, your fork opens the Web UI in the default browser where my UI credentials are saved. 
=> OK for this, I like it better than opening internally.
2) When entering userame/password in the Settings dialog, then nothing happens.
=>NOK on this part
I've not looked into the details right now
Here is my configuration (testing in a venv):
```
python 3.8.6
paho-mqtt  1.5.1
pip        20.2.1
PyQt5      5.15.1
PyQt5-sip  12.8.1
setuptools 49.2.1
```
If you have no clue, I will try to investigate point 2) durig the week-end
Thanks & best regards

**Comment by barbudor** [comment]
@373137461 I sent a PR to your fork.
Thanks

**Comment by jziolkowski** [comment]
In the next release I've decided to ditch the integrated WebUI browser tab. Now it defaults to opening the URL in default system browser.
