### ISSUE TITLE
TDM-009 # rule size to be adjusted to new options

### ISSUE THREAD

**Issue by riker65** [jziolkowski/tdm#93]
Hi
can the rulesize be adjusted to 1000 char?

Thanks

in documents: There are three separate rule sets called Rule1, Rule2 and Rule3. Each rule set can contain many rules which are dynamically compressed. Number of rules that can fit in a rule set varies. Expect at least 1000 characters available per rule set.

**Comment by jziolkowski** [comment]
I'll have to make it conditional based on the firmware version. I'll have look, but I hardly have time recently. Stay tuned.

**Comment by riker65** [comment]
Thanks perfect.

What happens at them moment (fW 8.3.) if rule is showing remaining <0 ? 
no upload ? 

Thanks
