### ISSUE TITLE
[Request] Support Device Name Field

### ISSUE THREAD

**Issue by Cerothen** [jziolkowski/tdm#94]
Please add a column for "Device Name" similar to friendly name.

Thanks and great software!

**Comment by barbudor** [comment]
Hi @jziolkowski , @Cerothen 
I would suggest to use `DeviceName` in place of `FiendlyName`  for devices running a firmware supporting it.
The first column could become `Name` and display `DeviceName` if it exist, or `FriendlyName` when it doesn't.
A new menu entry could then be created to allow configuring `DeviceName`, `FriendlyName<x>` 
Thanks

**Comment by jziolkowski** [comment]
Done in 0.2.8 enjoy :)
