### ISSUE TITLE
TDM-007 # fails to discover devices that have different "full topics" but same "topic variable" ie %topic%

### ISSUE THREAD

**Issue by w35m17h** [jziolkowski/tdm#95]
I have a device with full topic - %prefix%/sonoff/kitchen/%topic%/

![Screen Shot 2020-06-06 at 12 43 35 PM](https://user-images.githubusercontent.com/27325152/83951055-99a7ef00-a7f4-11ea-92ac-b10cd83ac8ec.png)

I have another device with full topic -%prefix%/sonoff/bar/%topic%/

![Screen Shot 2020-06-06 at 12 42 17 PM](https://user-images.githubusercontent.com/27325152/83951066-b0e6dc80-a7f4-11ea-9f74-24816f6aebf1.png)

Both have the variable %topic% set to 'lights'

These are my discovery strings in tdm...

![Screen Shot 2020-06-06 at 12 46 11 PM](https://user-images.githubusercontent.com/27325152/83951104-e986b600-a7f4-11ea-86e5-475ef25cef99.png)

tdm will only find ONE of the devices unless i remove the other offending search string. ie, if i remove the kitchen search string, it finds the bar lights device. If I remove the bar string, it finds the kitchen  lights device. If both search strings are in present, only the kitchen lights device is found. 

Am I doing something wrong? 

Thanks for any insight. 
Will.

**Comment by jziolkowski** [comment]
Will be fixed when #254 is merged.
